### ISSUE TITLE
Segmentation fault at creating tooltip (info about reg)

### ISSUE THREAD

**Issue by saruman9** [Vector35/binaryninja-api#1030]
OS: Linux 4.15.13-1-ARCH
Version: since 1.1.1177-dev Personal (Build ID 4fbb3761) to last dev version

When I move cursor to register `pc` or `r4` or `r5` or `r6` or others on line `0x412033f4`, occurs segmentation fault.
![error](https://user-images.githubusercontent.com/4244396/39232565-613e9b6c-4876-11e8-924e-eb287dc82965.png)

No errors occurs with others lines of disassembly. 

Registers:
```
$rax   : 0x00007fe67800b0c0  →  0x0000000000000001  →  0x0000000000000001
$rbx   : 0x00007ffda7872cc0  →  0x00457fff00170001
$rcx   : 0x00007ffda7872cc8  →  0x004600ff00000000
$rdx   : 0x0000000000000001  →  0x0000000000000001
$rsp   : 0x00007ffda7872c00  →  0x00000000030e6770  →  0x00007fe68cb6d790  →  0x00007fe68b085a70
$rbp   : 0x00007ffda7872c08  →  0x0000000000000000  →  0x0000000000000000
$rsi   : 0x00007fe67800b0c0  →  0x0000000000000001  →  0x0000000000000001
$rdi   : 0x0000000000000001  →  0x0000000000000001
$rip   : 0x00007fe68b043c33
$r8    : 0x0000000000000000  →  0x0000000000000000
$r9    : 0x00007fe67800b0c0  →  0x0000000000000001  →  0x0000000000000001
$r10   : 0xffffffffffffffff
$r11   : 0x00007ffda7873ef0  →  0x00000000e8bd8ef0
$r12   : 0x0000000000000000  →  0x0000000000000000
$r13   : 0x0000000000000000  →  0x0000000000000000
$r14   : 0x00007ffda7872cc0  →  0x00457fff00170001
$r15   : 0x00007ffda7873150  →  0x0000000000000001  →  0x0000000000000001
$eflags: [zero carry parity adjust sign trap INTERRUPT direction overflow RESUME virtualx86 identification]
$ds: 0x0000  $ss: 0x002b  $cs: 0x0033  $es: 0x0000  $fs: 0x0000  $gs: 0x0000
```
Full stack trace:
```
#0  0x00007fe68b043c33 in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#1  0x00007fe68b2d06aa in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#2  0x00007fe68b2d123e in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#3  0x00007fe68b2d25c5 in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#4  0x00007fe68b2ace90 in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#5  0x00007fe68b26c090 in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#6  0x00007fe68b1747a0 in ?? () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#7  0x00007fe68b1849eb in BNGetLowLevelILPossibleRegisterValuesAtInstruction () from /home/user/Downloads/binaryninja/libbinaryninjacore.so.1
No symbol table info available.
#8  0x0000000000562845 in BinaryNinja::LowLevelILFunction::GetPossibleRegisterValuesAtInstruction(unsigned int, unsigned long) ()
No symbol table info available.
#9  0x000000000048d9cf in DisassemblyView::hoverTimerEvent() ()
No symbol table info available.
#10 0x00007fe68929f229 in QMetaObject::activate(QObject*, int, int, void**) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#11 0x00007fe6892ab9e7 in QTimer::timeout(QTimer::QPrivateSignal) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#12 0x00007fe6892abcb8 in QTimer::timerEvent(QTimerEvent*) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#13 0x00007fe6892a013b in QObject::event(QEvent*) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#14 0x00007fe68a41b63c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/user/Downloads/binaryninja/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007fe68a422987 in QApplication::notify(QObject*, QEvent*) () from /home/user/Downloads/binaryninja/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007fe689274028 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#17 0x00007fe6892c768e in QTimerInfoList::activateTimers() () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#18 0x00007fe6892c7ea9 in ?? () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#19 0x00007fe68512a458 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#20 0x00007fe68512a6a1 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#21 0x00007fe68512a72e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#22 0x00007fe6892c81af in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#23 0x00007fe682f8bb81 in ?? () from /home/user/Downloads/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
No symbol table info available.
#24 0x00007fe68927289a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#25 0x00007fe68927b424 in QCoreApplication::exec() () from /home/user/Downloads/binaryninja/libQt5Core.so.5
No symbol table info available.
#26 0x000000000043cfe4 in main ()
```

**Comment by saruman9** [comment]
I can reproduce same crash on other PC.

**Comment by saruman9** [comment]
Yes, it's all good now. Thank you.
