### ISSUE TITLE
SIGABRT when where is no X server available

### ISSUE THREAD

**Issue by artemdinaburg** [Vector35/binaryninja-api#118]
binaryninja gets a SIGABRT and core dumps if there is no available X server.

```
artem@cgc2:~$ ~/binaryninja/binaryninja
QXcbConnection: Could not connect to display
Aborted (core dumped)

artem@cgc2:~$ /store/artem/gdb/bin/gdb --args ~/binaryninja/binaryninja
GNU gdb (GDB) 7.9.50.20150407-cvs
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/artem/binaryninja/binaryninja...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/artem/binaryninja/binaryninja
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
QXcbConnection: Could not connect to display

Program received signal SIGABRT, Aborted.
0x00007ffff5661cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff5661cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff56650d8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff62a213e in QMessageLogger::fatal(char const*, ...) const ()
   from /home/artem/binaryninja/libQt5Core.so.5
#3  0x00007fffead09e1e in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) ()
   from /home/artem/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#4  0x00007fffead0d696 in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) ()
   from /home/artem/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#5  0x00007fffeb02139b in ?? () from /home/artem/binaryninja/qt/platforms/libqxcb.so
#6  0x00007ffff6a33ad2 in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) () from /home/artem/binaryninja/libQt5Gui.so.5
#7  0x00007ffff6a3ed56 in QGuiApplicationPrivate::createPlatformIntegration() ()
   from /home/artem/binaryninja/libQt5Gui.so.5
#8  0x00007ffff6a3fabd in QGuiApplicationPrivate::createEventDispatcher() ()
   from /home/artem/binaryninja/libQt5Gui.so.5
#9  0x00007ffff64a6a36 in QCoreApplication::init() () from /home/artem/binaryninja/libQt5Core.so.5
#10 0x00007ffff64a6a96 in QCoreApplication::QCoreApplication(QCoreApplicationPrivate&) ()
   from /home/artem/binaryninja/libQt5Core.so.5
#11 0x00007ffff6a41d09 in QGuiApplication::QGuiApplication(QGuiApplicationPrivate&) ()
   from /home/artem/binaryninja/libQt5Gui.so.5
#12 0x00007ffff72bf91d in QApplication::QApplication(int&, char**, int) ()
   from /home/artem/binaryninja/libQt5Widgets.so.5
#13 0x0000000000423f15 in BinaryNinjaApplication::BinaryNinjaApplication(int&, char**) ()
#14 0x000000000042259a in main ()
(gdb)
```

**Comment by psifertex** [comment]
This is expected behavior -- if desired to run in a headless operation, the core should be either used via python or c API. Alternatively, it is possible to run via ssh X forwarding if that's what you desire. I thought from another comment that's what you were referring to, can you clarify?

**Comment by artemdinaburg** [comment]
So my issue is that binary ninja SIGABRTs and core dumps. I can understand that it wont start without X support, but core dump seems like a really bad way to let people know.

**Comment by psifertex** [comment]
Reviewing some old bugs and removing this completely. We've got the headless build intended for truly X-less environments, and don't plan to support linux servers without X libraries for X-forwarding, primarily because it's a Qt issue that would likely require too much infrastructure to work around.
