### ISSUE TITLE
parse_types_from_source does not parse enums with negative values

### ISSUE THREAD

**Issue by irwincong** [Vector35/binaryninja-api#1263]
```python
>>> bv.platform.parse_types_from_source("enum colors_t { RED, GREEN, BLUE };")
<types: {'colors_t': <type: enum>}, variables: {}, functions: {}>

>>> bv.platform.parse_types_from_source("enum colors_t { RED=1, GREEN, BLUE };")
<types: {'colors_t': <type: enum>}, variables: {}, functions: {}>

>>> bv.platform.parse_types_from_source("enum colors_t { RED=-1, GREEN, BLUE };")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/binaryninja/python/binaryninja/platform.py", line 402, in parse_types_from_source
    raise SyntaxError(error_str)
SyntaxError: input:1: error: syntax error
```

**Comment by plafosse** [comment]
Fixed as of 2.0.2153
