### ISSUE TITLE
Triage/binaryninjaui Breaks Headless Mode

### ISSUE THREAD

**Issue by sraboy** [Vector35/binaryninja-api#1343]
With **1.1.1635-dev (Build d8c2f206)**

When Triage is installed and I run Binja headless with Python 3.6, the Python2(??) version of libshiboken2 throws an exception:

```
In [1]: from binaryninja import * 
   ...: bv = binaryninja.BinaryViewType['ELF'].open('/tmp/example_1.bin') 
   ...: bv.update_analysis_and_wait()                                                                                   
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.binaryninja/plugins/triage/__init__.py in <module>
----> 1 from . import view
      2 from . import byte
      3 from . import files

~/.binaryninja/plugins/triage/view.py in <module>
      1 import traceback
----> 2 import binaryninjaui
      3 from binaryninja.settings import Settings
      4 from binaryninja import log
      5 from binaryninjaui import View, ViewType, UIContext, ViewFrame

ImportError: /usr/local/bin/binaryninja/python2/shiboken2/libshiboken2-python2.7.x86_64-linux-gnu.so.5.12: undefined symbol: _Py_ZeroStruct

```

I'm unsure if `binaryninjaui` cannot be imported in headless mode (which is a bug IMO) or if I need to do something to make `binaryninjaui` accessible to Python3.

**Comment by psifertex** [comment]
Thanks, this is a known issue we plan to fix before the next stable but didn't have an issue tracking it.

**Comment by psifertex** [comment]
Sorry, it looks like it's an issue with the `install_api.py` script. You can manually fix with:
```
sed -i '' '/python3/d' `python2 -c 'import os;from site import getusersitepackages;print(os.path.join(getusersitepackages(),"binaryninja.pth"));'`
sed -i '' '/python2/d' `python3 -c 'import os;from site import getusersitepackages;print(os.path.join(getusersitepackages(),"binaryninja.pth"));'`
```
And builds > 1638 should have the updated install script.

**Comment by sraboy** [comment]
I pulled the latest `install_api.py` script to be sure I didn't screw anything up. Still an issue with headless:

```
In [1]: import binaryninjaui                                                                                            
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ef1ffead2fff> in <module>
----> 1 import binaryninjaui

ImportError: could not import module 'PySide2.QtWidgets'
```

**Comment by sraboy** [comment]
```
(env:angrdev) steve@xubuntudev:/usr/local/bin/binaryninja$ rm /home/steve/.pyenv/angrdev/lib/python3.6/site-packages/binaryninja.pth 
(env:angrdev) steve@xubuntudev:/usr/local/bin/binaryninja$ python3 scripts/install_api.py 
Found install folder of /usr/local/bin/binaryninja/python
Found Binary Ninja core version: 1.1.1638-dev
Binary Ninja API installed using /home/steve/.pyenv/angrdev/lib/python3.6/site-packages/binaryninja.pth
(env:angrdev) steve@xubuntudev:/usr/local/bin/binaryninja$ ipython
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import binaryninjaui                                                                                                                                
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ef1ffead2fff> in <module>
----> 1 import binaryninjaui

ImportError: could not import module 'PySide2.QtWidgets'
```

**Comment by psifertex** [comment]
Did you remove and re-generate your PTH files? I'm about to push another change to the installer that will forcibly overwrite those files since they should only be generated by the same script which will make migration easier. 

I just tested in ipython and I couldn't reproduce that.

**Comment by sraboy** [comment]
Now on `Version 1.1.1640-dev (Build ID bae62dc6)` (Ubuntu 18.04.2/bionic):

```
In [1]: import binaryninjaui                                                                                                                                
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-ef1ffead2fff> in <module>
----> 1 import binaryninjaui

/usr/local/bin/binaryninja/python3/binaryninjaui/__init__.py in <module>
      7 # method is called with invalid arguments.
      8 import sys
----> 9 sys.modules['shiboken2.shiboken2.support.signature.mapping'].update_mapping.__self__._uninitialized += ['binaryninjaui']
     10 def _init_binaryninjaui():
     11         return locals()

KeyError: 'shiboken2.shiboken2.support.signature.mapping'

In [2]: import sys                                                                                                                                          

In [3]: mods = [m for m in sys.modules.keys() if 'shiboken' in m]                                                                                           

In [4]: mods                                                                                                                                                
Out[4]: ['shiboken2', 'shiboken2.shiboken2']

In [5]: import shiboken2.support.signature.mapping                                                                                                          

In [6]: shiboken2.__version__                                                                                                                               
Out[6]: '5.12.0'
```

**Comment by sraboy** [comment]
So, with more tinkering, things will still work but errors are dumped to stdout:

```
In [1]: from binaryninja import * 
   ...: bv = binaryninja.BinaryViewType['ELF'].open('/bin/true') 
   ...: bv.update_analysis_and_wait() 
   ...: print('*** Analysis Done! Entry symbol: {}'.format(bv.get_symbol_at(bv.entry_point)))                                                               
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.binaryninja/plugins/triage/__init__.py in <module>
----> 1 from . import view
      2 from . import byte
      3 from . import files

~/.binaryninja/plugins/triage/view.py in <module>
      1 import traceback
----> 2 import binaryninjaui
      3 from binaryninja.settings import Settings
      4 from binaryninja import log
      5 from binaryninjaui import View, ViewType, UIContext, ViewFrame

/usr/local/bin/binaryninja/python3/binaryninjaui/__init__.py in <module>
      7 # method is called with invalid arguments.
      8 import sys
----> 9 sys.modules['shibokensupport.signature.mapping'].update_mapping.__self__._uninitialized += ['binaryninjaui']
     10 def _init_binaryninjaui():
     11         return locals()

KeyError: 'shibokensupport.signature.mapping'
*** Analysis Done! Entry symbol: <SymbolType.FunctionSymbol: "_start" @ 0x17b0>
```

However, it's not specific to IPython:

```
(env:angrdev) steve@xubuntudev:/usr/local/bin/binaryninja$ python -c "from binaryninja import *; bv = binaryninja.BinaryViewType['ELF'].open('/bin/ls'); bv.update_analysis_and_wait(); print('*** Analysis Done! Entry symbol: {}'.format(bv.get_symbol_at(bv.entry_point)))"
Traceback (most recent call last):
  File "/home/steve/.binaryninja/plugins/triage/__init__.py", line 1, in <module>
    from . import view
  File "/home/steve/.binaryninja/plugins/triage/view.py", line 2, in <module>
    import binaryninjaui
  File "/usr/local/bin/binaryninja/python3/binaryninjaui/__init__.py", line 9, in <module>
    sys.modules['shibokensupport.signature.mapping'].update_mapping.__self__._uninitialized += ['binaryninjaui']
KeyError: 'shibokensupport.signature.mapping'
*** Analysis Done! Entry symbol: <SymbolType.FunctionSymbol: "_start" @ 0x5850>
```

Of course, conditionally importing based on `'shibokensupport.signature.mapping' in sys.modules` means `binaryninjaui` is missing types so we instead get `ImportError`:
```
In [1]: from binaryninja import * 
   ...: bv = binaryninja.BinaryViewType['ELF'].open('/bin/true') 
   ...: bv.update_analysis_and_wait() 
   ...: print('*** Analysis Done! Entry symbol: {}'.format(bv.get_symbol_at(bv.entry_point)))                                                               
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.binaryninja/plugins/triage/__init__.py in <module>
----> 1 from . import view
      2 from . import byte
      3 from . import files

~/.binaryninja/plugins/triage/view.py in <module>
      3 from binaryninja.settings import Settings
      4 from binaryninja import log
----> 5 from binaryninjaui import View, ViewType, UIContext, ViewFrame
      6 from PySide2.QtWidgets import QScrollArea, QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QGroupBox, QSplitter
      7 from PySide2.QtCore import Qt

ImportError: cannot import name 'View'
*** Analysis Done! Entry symbol: <SymbolType.FunctionSymbol: "_start" @ 0x17b0>
```

At least things work but with multiple UI plugins installed, this gets really verbose. I think the only solution would be for Binja to not load `ui` plugins in headless mode. The workaround for now is to wrap the plugins' imports in a `core_ui_enabled()` check.

**Comment by psifertex** [comment]
So yeah, as I mentioned above this definitely looks like you have a different version of pyside2 installed that's being loaded before the one we ship with.  Can you double check with a clean shell and:
```
import PySide2
import sys
print sys.modules['PySide2']
```
to see where it's being loaded from? If you modify `sys.path` to load from the BN install folders first, that should likely fix it.

**Comment by psifertex** [comment]
Oh sorry, whoops. My previous comment about different pyside versions didn't actually get submitted. Sorry about that. :-)

**Comment by sraboy** [comment]
Okay, that's it. I had `5.12.0` but you guys ship `5.12.3`.

**Comment by psifertex** [comment]
We actually just rev'ed to 5.12.3 in that last update. The previous version /was/ 5.12.0 so I'm not sure what caused that issue, but glad it's working!
