### ISSUE TITLE
Headless mode on Windows fails to load with non-ASCII username

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#1355]
Trying to use headless on WIndows with non-ASCII characters in the username can cause exceptions when trying to load the Binary Ninja API

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\いちろ\AppData\Local\Vector35\BinaryNinja\python\binaryninja\__init__.py", line 100, in <module>
    import binaryninja._binaryninjacore as core
  File "c:\Users\いちろ\AppData\Local\Vector35\BinaryNinja\python\binaryninja\_binaryninjacore.py", line 13574, in <module>
    BNSetBundledPluginDirectory(os.path.join(_base_path, "plugins"))
  File "c:\Users\いちろ\AppData\Local\Vector35\BinaryNinja\python\binaryninja\_binaryninjacore.py", line 12284, in BNSetBundledPluginDirectory
    return _BNSetBundledPluginDirectory(cstr(args[0]))
  File "c:\Users\いちろ\AppData\Local\Vector35\BinaryNinja\python\binaryninja\__init__.py", line 89, in cstr
    return arg.encode('charmap')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-11: ordinal not in range(256)

**Comment by KyleMiles** [comment]
Should be fixed in 1.1.1768-dev.
