### ISSUE TITLE
Handle invalid address in BinaryView.get_ascii_string_at

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1360]
`BinaryView.get_ascii_string_at` throws an exception rather than returns `None` if the address passed in is invalid. This should be changed.

```
>>> bv.get_ascii_string_at(0, 1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 3452, in get_ascii_string_at
    while c > 0 and c <= 0x7f:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by KyleMiles** [comment]
Resolved with 0b82a65baf409d8325f9a6012750356088ab20e2.
