### ISSUE TITLE
Bug in Assembler x86

### ISSUE THREAD

**Issue by secretsquirrel** [Vector35/binaryninja-api#1388]
While doing some code rewriting I found a couple instruction bugs in the arch x86 assembler (I haven't looked at x86_64 as of yet, but I will soon...):

```
bv.arch.assemble("movdqa  xmmword [edi+0x70], xmm7")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/architecture.py", line 2415, in assemble
    raise ValueError("Could not assemble: %s" % error_str)
ValueError: Could not assemble: b": error: warnings being treated as errors\ninput:1: error: undefined symbol `xmmword' (first use)\ninput:1: error:  (Each undefined symbol is reported only once.)\n"
```

So to help find issues around this I just ran assemble() on get_disassembly() output on a larger windows EXE  and compiled a list of at fault instructions:

```
Could not assemble: b": error: warnings being treated as errors\ninput:1: error: undefined symbol `xmmword' (first use)\ninput:1: error:  (Each undefined symbol is reported only once.)\n" Cause: movdqa  xmm0, xmmword [esi] | Bytes: 660f6f06
Could not assemble: b": error: warnings being treated as errors\ninput:1: error: undefined symbol `xmmword' (first use)\ninput:1: error:  (Each undefined symbol is reported only once.)\n" Cause: movdqa  xmm1, xmmword [esi+0x10] | Bytes: 660f6f4e10
Could not assemble: b": error: warnings being treated as errors\ninput:1: error: undefined symbol `xmmword' (first use)\ninput:1: error:  (Each undefined symbol is reported only once.)\n" Cause: movdqa  xmmword [edi+0x10], xmm0 | Bytes: 660f7f4710
Could not assemble: b": error: warnings being treated as errors\ninput:1: error: undefined symbol `xmmword' (first use)\ninput:1: error:  (Each undefined symbol is reported only once.)\n" Cause: movdqa  xmmword [edi], xmm0 | Bytes: 660f7f07
```
You can assume any iteration of `movdqa  xmmword [<valid register>], xmmX` or `movdqa  xmmX xmmword [<valid register>+0xX]` will have this bug.

```
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid combination of opcode and operands\n' Cause: movsd   dword [edi], [esi] | Bytes: a5
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid combination of opcode and operands\n' Cause: rep movsd dword [edi], [esi] | Bytes: f3a5
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid number of operands\n' Cause: movsw   word [edi], [esi] | Bytes: 66a5
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid number of operands\n' Cause: rep movsb byte [edi], [esi] | Bytes: f3a4
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid number of operands\n' Cause: rep stosb byte [edi] | Bytes: f3aa
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid number of operands\n' Cause: rep stosd dword [edi] | Bytes: f3ab
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid number of operands\n' Cause: repne scasb byte [edi] | Bytes: f2ae
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid number of operands\n' Cause: stosd   dword [edi] | Bytes: ab
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid size for operand 1\n' Cause: fld     [0x44697c] | Bytes: db2d7c694400
Could not assemble: b': error: warnings being treated as errors\ninput:1: error: invalid size for operand 1\n' Cause: fld     [0x446988] | Bytes: db2d88694400_
```

I can work around this in the short term by catching exceptions and handling each instruction individually. But it's not ideal. :)

**Comment by plafosse** [comment]
We actually just use Yasm on the back end for assembling x86 yasm uses `oword` instead of `xmmword`  This works just fine: `Architecture['x86_64'].assemble("movdqa oword [edi+0x70], xmm7")`

**Comment by secretsquirrel** [comment]
👍
