### ISSUE TITLE
Import error in functionrecognizer.py

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1414]
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/functionrecognizer.py", line 77, in _recognize_medium_level_il
    log.log_error(traceback.format_exc())
AttributeError: 'function' object has no attribute 'log_error'
```

**Comment by plafosse** [comment]
Did you perhaps call your function object in your call back 'log' cause this doesn't make sense.

**Comment by psifertex** [comment]
Pretty sure this is just an issue with a name collision, if that's not the case and there's no "log" in the namespace, feel free to reopen and I can take another look.
