### ISSUE TITLE
BinaryNinja seems to attempt to free a bad pointer while parsing types

### ISSUE THREAD

**Issue by irwincong** [Vector35/binaryninja-api#1447]
I can consistently cause BinaryNinja to crash.  I have not spent time to investigate if I can do anything with the crash, but at one point I did get a message saying that free was trying to free a bad pointer.

Recreate:
1. Use BinaryNinja v1.1.1689
2. Load a 64-bit Intel binary (e.g., `/bin/ls`) and wait for autoanalysis to complete.  (NOTE: I am not sure the arch matters, but this was what I tested with).
3. `bv.platform.parse_types_from_source('#include "/tmp/tmppkCzvp.h"; int test;')`

The header file that I was using is attached (with .txt appended)
[tmppkCzvp.h.txt](https://github.com/Vector35/binaryninja-api/files/3622549/tmppkCzvp.h.txt)

Without `typedef bool  (* google::protobuf::internal::EnumValidityFunc) (int32_t);` in the file, it seems to parse fine.  If I only parse the types from the `#include` statement (rather than parsing from file), it seems to parse fine.

```
$ gdb --args /home/iong/binaryninja/binaryninja -d -l binaryninja.log /bin/ls
Reading symbols from /home/iong/binaryninja/binaryninja...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/iong/binaryninja/binaryninja -d -l binaryninja.log /bin/ls
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec490700 (LWP 14152)]
[New Thread 0x7fffeb745700 (LWP 14153)]
[New Thread 0x7fffeaf44700 (LWP 14154)]
[New Thread 0x7fffd75d3700 (LWP 14157)]
[New Thread 0x7fffd659b700 (LWP 14158)]
[New Thread 0x7fffd5d9a700 (LWP 14159)]
[New Thread 0x7fffd5599700 (LWP 14160)]
[New Thread 0x7fffd4d98700 (LWP 14161)]
[New Thread 0x7fffcffff700 (LWP 14162)]
[New Thread 0x7fffcf7fe700 (LWP 14163)]
[New Thread 0x7fffceffd700 (LWP 14164)]
[New Thread 0x7fffce7fc700 (LWP 14165)]
[New Thread 0x7fffcdffb700 (LWP 14166)]
[Thread 0x7fffd75d3700 (LWP 14157) exited]
[New Thread 0x7fffd75d3700 (LWP 14174)]
[Thread 0x7fffd75d3700 (LWP 14174) exited]
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

Thread 6 "binaryninja" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd659b700 (LWP 14158)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

BinaryNinja logs did not have anything useful (that I can tell).

GDB backtrace below.

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff3726801 in __GI_abort () at abort.c:79
#2  0x00007ffff4119957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff411fab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff411faf1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff411fd24 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff411b797 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff67fdacd in ?? () from /home/iong/binaryninja/libbinaryninjacore.so.1
#8  0x00007ffff664a1cc in ?? () from /home/iong/binaryninja/libbinaryninjacore.so.1
#9  0x00007ffff6656645 in ?? () from /home/iong/binaryninja/libbinaryninjacore.so.1
#10 0x00007ffff6657e4f in BNParseTypesFromSource () from /home/iong/binaryninja/libbinaryninjacore.so.1
#11 0x00007fffda6d5dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#12 0x00007fffda6d571f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#13 0x00007fffda8e8ad4 in _call_function_pointer (argcount=8, resmem=0x7fffd65999b0, restype=<optimized out>, atypes=0x7fffd6599910, avalues=0x7fffd6599960, pProc=0x7ffff6657b40 <BNParseTypesFromSource>, flags=4353) at ./Modules/_ctypes/callproc.c:841
#14 _ctypes_callproc () at ./Modules/_ctypes/callproc.c:1184
#15 0x00007fffda8e84d5 in PyCFuncPtr_call () at ./Modules/_ctypes/_ctypes.c:4076
#16 0x00007fffdae824a3 in PyObject_Call (func=<_FuncPtr(__name__='BNParseTypesFromSource') at remote 0x7fffd96d4ef0>, arg=<optimized out>, kw=<optimized out>) at ../Objects/abstract.c:2544
#17 0x00007fffdaed762e in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fffd6599d30, func=<optimized out>) at ../Python/ceval.c:4589
#18 call_function (oparg=<optimized out>, pp_stack=0x7fffd6599d30) at ../Python/ceval.c:4394
#19 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3009
#20 0x00007fffdb00dbf8 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fffc802b228, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3604
#21 0x00007fffdaedb904 in fast_function (nk=<optimized out>, na=<optimized out>, n=8, pp_stack=0x7fffd6599f10, func=<optimized out>) at ../Python/ceval.c:4467
#22 call_function (oparg=<optimized out>, pp_stack=0x7fffd6599f10) at ../Python/ceval.c:4392
#23 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3009
#24 0x00007fffdb00dbf8 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fffd7642538, kwcount=0, defs=0x7fffd9403338, defcount=3, closure=0x0) at ../Python/ceval.c:3604
#25 0x00007fffdaedb904 in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fffd659a0f0, func=<optimized out>) at ../Python/ceval.c:4467
#26 call_function (oparg=<optimized out>, pp_stack=0x7fffd659a0f0) at ../Python/ceval.c:4392
#27 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3009
#28 0x00007fffdb00dbf8 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3604
#29 0x00007fffdaed5409 in PyEval_EvalCode (co=co@entry=0x7fffd79bed30, globals=globals@entry={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper '__lt__' of type object at 0x7fffdb36ebe0>, __reduce_ex__=<instancemethod at remote 0x7fffd964ad20>, __new__=<staticmethod at remote 0x7fffd964f8a0>, _value2member_map_={0: <...>, 1: <AnalysisState(_value_=1, __objclass__=<...>, _name_='DisassembleState') at remote 0x7fffd965b5a8>, 2: <AnalysisState(_value_=2, __objclass__=<...>, _name_='AnalyzeState') at remote 0x7fffd965b5f0>, 3: <AnalysisState(_value_=3, __objclass__=<...>, _name_='ExtendedAnalyzeState') at remote 0x7fffd965b680>}, __format__=<instancemethod at remote 0x7fffd964a5f0>, _member_names_=['IdleState', 'DisassembleState', 'AnalyzeState', 'ExtendedAnalyzeState'], _member_map_=<OrderedDict(_OrderedDict__root=[[[[[[...], [...], 'IdleState'], [...], '...(truncated), locals=locals@entry={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper '__lt__' of type object at 0x7fffdb36ebe0>, __reduce_ex__=<instancemethod at remote 0x7fffd964ad20>, __new__=<staticmethod at remote 0x7fffd964f8a0>, _value2member_map_={0: <...>, 1: <AnalysisState(_value_=1, __objclass__=<...>, _name_='DisassembleState') at remote 0x7fffd965b5a8>, 2: <AnalysisState(_value_=2, __objclass__=<...>, _name_='AnalyzeState') at remote 0x7fffd965b5f0>, 3: <AnalysisState(_value_=3, __objclass__=<...>, _name_='ExtendedAnalyzeState') at remote 0x7fffd965b680>}, __format__=<instancemethod at remote 0x7fffd964a5f0>, _member_names_=['IdleState', 'DisassembleState', 'AnalyzeState', 'ExtendedAnalyzeState'], _member_map_=<OrderedDict(_OrderedDict__root=[[[[[[...], [...], 'IdleState'], [...], '...(truncated)) at ../Python/ceval.c:669
#30 0x00007fffdaedbe45 in exec_statement (locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper '__lt__' of type object at 0x7fffdb36ebe0>, __reduce_ex__=<instancemethod at remote 0x7fffd964ad20>, __new__=<staticmethod at remote 0x7fffd964f8a0>, _value2member_map_={0: <...>, 1: <AnalysisState(_value_=1, __objclass__=<...>, _name_='DisassembleState') at remote 0x7fffd965b5a8>, 2: <AnalysisState(_value_=2, __objclass__=<...>, _name_='AnalyzeState') at remote 0x7fffd965b5f0>, 3: <AnalysisState(_value_=3, __objclass__=<...>, _name_='ExtendedAnalyzeState') at remote 0x7fffd965b680>}, __format__=<instancemethod at remote 0x7fffd964a5f0>, _member_names_=['IdleState', 'DisassembleState', 'AnalyzeState', 'ExtendedAnalyzeState'], _member_map_=<OrderedDict(_OrderedDict__root=[[[[[[...], [...], 'IdleState'], [...], '...(truncated), globals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper '__lt__' of type object at 0x7fffdb36ebe0>, __reduce_ex__=<instancemethod at remote 0x7fffd964ad20>, __new__=<staticmethod at remote 0x7fffd964f8a0>, _value2member_map_={0: <...>, 1: <AnalysisState(_value_=1, __objclass__=<...>, _name_='DisassembleState') at remote 0x7fffd965b5a8>, 2: <AnalysisState(_value_=2, __objclass__=<...>, _name_='AnalyzeState') at remote 0x7fffd965b5f0>, 3: <AnalysisState(_value_=3, __objclass__=<...>, _name_='ExtendedAnalyzeState') at remote 0x7fffd965b680>}, __format__=<instancemethod at remote 0x7fffd964a5f0>, _member_names_=['IdleState', 'DisassembleState', 'AnalyzeState', 'ExtendedAnalyzeState'], _member_map_=<OrderedDict(_OrderedDict__root=[[[[[[...], [...], 'IdleState'], [...], '...(truncated), prog=<optimized out>, f=Frame 0x7fffd79f4050, for file /usr/lib/python2.7/code.py, line 103, in runcode (self=<InteractiveConsole(compile=<CommandCompiler(compiler=<Compile(flags=512) at remote 0x7fffd79d2b90>) at remote 0x7fffd79d2ef0>, buffer=[u'bv.platform.parse_types_from_source(\'#include "/tmp/tmppkCzvp.h"; int test;\')'], locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper '__lt__' of type object at 0x7fffdb36ebe0>, __reduce_ex__=<instancemethod at remote 0x7fffd964ad20>, __new__=<staticmethod at remote 0x7fffd964f8a0>, _value2member_map_={0: <...>, 1: <AnalysisState(_value_=1, __objclass__=<...>, _name_='DisassembleState') at remote 0x7fffd965b5a8>, 2: <AnalysisState(_value_=2, __objclass__=<...>, _name_='AnalyzeState') at remote 0x7fffd965b5f0>, 3: <AnalysisState(_value...(truncated)) at ../Python/ceval.c:5089
#31 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:2118
#32 0x00007fffdb00dbf8 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fffd9380800, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3604
#33 0x00007fffdaedb904 in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fffd659a4c0, func=<optimized out>) at ../Python/ceval.c:4467
#34 call_function (oparg=<optimized out>, pp_stack=0x7fffd659a4c0) at ../Python/ceval.c:4392
#35 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3009
#36 0x00007fffdb00dbf8 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fffd8e5aee8, kwcount=0, defs=0x7fffd93de9b0, defcount=2, closure=0x0) at ../Python/ceval.c:3604
#37 0x00007fffdaedb904 in fast_function (nk=<optimized out>, na=<optimized out>, n=3, pp_stack=0x7fffd659a6a0, func=<optimized out>) at ../Python/ceval.c:4467
#38 call_function (oparg=<optimized out>, pp_stack=0x7fffd659a6a0) at ../Python/ceval.c:4392
#39 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffd8e5ad38, for file /usr/lib/python2.7/code.py, line 265, in push (self=<InteractiveConsole(compile=<CommandCompiler(compiler=<Compile(flags=512) at remote 0x7fffd79d2b90>) at remote 0x7fffd79d2ef0>, buffer=[u'bv.platform.parse_types_from_source(\'#include "/tmp/tmppkCzvp.h"; int test;\')'], locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper '__lt__' of type object at 0x7fffdb36ebe0>, __reduce_ex__=<instancemethod at remote 0x7fffd964ad20>, __new__=<staticmethod at remote 0x7fffd964f8a0>, _value2member_map_={0: <...>, 1: <AnalysisState(_value_=1, __objclass__=<...>, _name_='DisassembleState') at remote 0x7fffd965b5a8>, 2: <AnalysisState(_value_=2, __objclass__=<...>, _name_='AnalyzeState') at remote 0x7fffd965b5f0>, 3: <AnalysisState(_value_=3...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:3009
#40 0x00007fffdaedc81c in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fffd659a7c0, func=<optimized out>) at ../Python/ceval.c:4457
#41 call_function (oparg=<optimized out>, pp_stack=0x7fffd659a7c0) at ../Python/ceval.c:4392
#42 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffd79f6050, for file /home/iong/binaryninja/plugins/../python/binaryninja/scriptingprovider.py, line 574, in run (self=<InterpreterThread(_Thread__ident=140736789591808, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fffe803b630>, acquire=<built-in method acquire of thread.lock object at remote 0x7fffe803b630>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fffe803b630>) at remote 0x7fffd79c9910>) at remote 0x7fffd79c9750>, code=None, interpreter=<InteractiveConsole(compile=<CommandCompiler(compiler=<Compile(flags=512) at remote 0x7fffd79d2b90>) at remote 0x7fffd79d2ef0>, buffer=[u'bv.platform.parse_types_from_source(\'#include "/tmp/tmppkCzvp.h"; int test;\')'], locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:3009
#43 0x00007fffdaedc81c in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffd659a8e0, func=<optimized out>) at ../Python/ceval.c:4457
#44 call_function (oparg=<optimized out>, pp_stack=0x7fffd659a8e0) at ../Python/ceval.c:4392
#45 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffc8000b70, for file /usr/lib/python2.7/threading.py, line 801, in __bootstrap_inner (self=<InterpreterThread(_Thread__ident=140736789591808, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fffe803b630>, acquire=<built-in method acquire of thread.lock object at remote 0x7fffe803b630>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fffe803b630>) at remote 0x7fffd79c9910>) at remote 0x7fffd79c9750>, code=None, interpreter=<InteractiveConsole(compile=<CommandCompiler(compiler=<Compile(flags=512) at remote 0x7fffd79d2b90>) at remote 0x7fffd79d2ef0>, buffer=[u'bv.platform.parse_types_from_source(\'#include "/tmp/tmppkCzvp.h"; int test;\')'], locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:3009
#46 0x00007fffdaedc81c in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffd659aa00, func=<optimized out>) at ../Python/ceval.c:4457
#47 call_function (oparg=<optimized out>, pp_stack=0x7fffd659aa00) at ../Python/ceval.c:4392
#48 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3009
#49 0x00007fffdb00dbf8 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3604
#50 0x00007fffdafae8e9 in function_call.lto_priv.345 (func=<function at remote 0x7fffda64d500>, arg=(<InterpreterThread(_Thread__ident=140736789591808, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fffe803b630>, acquire=<built-in method acquire of thread.lock object at remote 0x7fffe803b630>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fffe803b630>) at remote 0x7fffd79c9910>) at remote 0x7fffd79c9750>, code=None, interpreter=<InteractiveConsole(compile=<CommandCompiler(compiler=<Compile(flags=512) at remote 0x7fffd79d2b90>) at remote 0x7fffd79d2ef0>, buffer=[u'bv.platform.parse_types_from_source(\'#include "/tmp/tmppkCzvp.h"; int test;\')'], locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper...(truncated), kw=0x0) at ../Objects/funcobject.c:523
#51 0x00007fffdae824a3 in PyObject_Call (func=<function at remote 0x7fffda64d500>, arg=<optimized out>, kw=<optimized out>) at ../Objects/abstract.c:2544
#52 0x00007fffdafda50c in instancemethod_call.lto_priv.261 (func=<function at remote 0x7fffda64d500>, arg=(<InterpreterThread(_Thread__ident=140736789591808, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fffe803b630>, acquire=<built-in method acquire of thread.lock object at remote 0x7fffe803b630>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fffe803b630>) at remote 0x7fffd79c9910>) at remote 0x7fffd79c9750>, code=None, interpreter=<InteractiveConsole(compile=<CommandCompiler(compiler=<Compile(flags=512) at remote 0x7fffd79d2b90>) at remote 0x7fffd79d2ef0>, buffer=[u'bv.platform.parse_types_from_source(\'#include "/tmp/tmppkCzvp.h"; int test;\')'], locals={'AnalysisState': <EnumMeta(__module__='binaryninja.enums', __ne__=<method-wrapper '__ne__' of type object at 0x7fffdb36ebe0>, __str__=<instancemethod at remote 0x7fffd9b54cd0>, IdleState=<AnalysisState(_value_=0, __objclass__=<...>, _name_='IdleState') at remote 0x7fffd965b560>, __lt__=<method-wrapper...(truncated), kw=0x0) at ../Objects/classobject.c:2600
#53 0x00007fffdae824a3 in PyObject_Call (func=<instancemethod at remote 0x7fffd79c4af0>, arg=<optimized out>, kw=<optimized out>) at ../Objects/abstract.c:2544
#54 0x00007fffdb00d127 in PyEval_CallObjectWithKeywords (func=<instancemethod at remote 0x7fffd79c4af0>, arg=(), kw=<optimized out>) at ../Python/ceval.c:4241
#55 0x00007fffdaf08392 in t_bootstrap (boot_raw=0x1792370) at ../Modules/threadmodule.c:620
#56 0x00007ffff441d6db in start_thread (arg=0x7fffd659b700) at pthread_create.c:463
#57 0x00007ffff380788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by psifertex** [comment]
Appreciate the bug report -- crashing bugs tend to get triaged very quickly, but I did want to ask if you've tried on the latest dev or not yet? There have been a /ton/ of fixes that have landed there over the past three and a half months.

**Comment by D0ntPanic** [comment]
Fixed in build 2003
