### ISSUE TITLE
version_switcher.py example does not work in python3

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1477]
```
Requesting update to prior version.
version.version 1.2.1922-dev
core_version 1.2.1923-dev
Downloading...
^[UpdateResult.UpdateSuccess
Installing...
Traceback (most recent call last):
  File "version_switcher.py", line 151, in <module>
    main()
  File "version_switcher.py", line 147, in main
    select(versions[selection - 1])
  File "version_switcher.py", line 85, in select
    install_pending_update()
  File "/Applications/Binary Ninja-dev.app/Contents/Resources/python/binaryninja/update.py", line 328, in install_pending_update
    raise IOError(error_str)
OSError: b''
```

**Comment by plafosse** [comment]
Fixed in 1.2.1970
