### ISSUE TITLE
BNParseTypesFromSource-related crash

### ISSUE THREAD

**Issue by meme** [Vector35/binaryninja-api#1506]
Sample as provided by @verylazyguy:
```python
bv.platform.parse_types_from_source("typedef struct struct_name { int member; } typename;")
```

Results in the following crash:

```
Thread 22 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8e7fc700 (LWP 51800)]
0x0000000000000004 in ?? ()
(gdb) bt
#0  0x0000000000000004 in ?? ()
#1  0x00007ffff629b4a3 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff629c8ff in BNParseTypesFromSource () from /opt/binaryninja/libbinaryninjacore.so.1
```

This issue does not occur on stable, and does occur on 1.2.1988-dev. It has been around for the last few releases.

**Comment by D0ntPanic** [comment]
Fixed in build 2002
