### ISSUE TITLE
1.3.2024-dev (1.3.2023 broken as well) Existing Database Segfault 

### ISSUE THREAD

**Issue by Knight-Ops** [Vector35/binaryninja-api#1525]
The latest update has introduced a crash when opening certain existing databases.

```
gef➤  run
Starting program: /usr/bin/bn 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe1389700 (LWP 23913)]
[New Thread 0x7fffd9e3a700 (LWP 23914)]
[New Thread 0x7fffd9639700 (LWP 23915)]
[New Thread 0x7fffc6aee700 (LWP 23919)]
[New Thread 0x7fffc62ed700 (LWP 23924)]
[New Thread 0x7fffc5aec700 (LWP 23925)]
[New Thread 0x7fffc52eb700 (LWP 23926)]
[New Thread 0x7fffc4aea700 (LWP 23927)]
[New Thread 0x7fffaffff700 (LWP 23928)]
[New Thread 0x7fffaf7fe700 (LWP 23929)]
[New Thread 0x7fffaeffd700 (LWP 23930)]
[New Thread 0x7fffadffb700 (LWP 23932)]
[New Thread 0x7fffae7fc700 (LWP 23931)]
[New Thread 0x7fffad7fa700 (LWP 23933)]
[New Thread 0x7fffacff9700 (LWP 23934)]
[New Thread 0x7fff97fff700 (LWP 23935)]
[New Thread 0x7fff977fe700 (LWP 23936)]
[New Thread 0x7fff967fc700 (LWP 23938)]
[New Thread 0x7fff96ffd700 (LWP 23937)]
[New Thread 0x7fff95ffb700 (LWP 23939)]
[New Thread 0x7fff957fa700 (LWP 23941)]
gef➤  [New Thread 0x7fff83fff700 (LWP 23953)]
[Thread 0x7fff95ffb700 (LWP 23939) exited]
[New Thread 0x7fff95ffb700 (LWP 23955)]
[23896:23926:0211/143249.188957:ERROR:nss_util.cc(748)] After loading Root Certs, loaded==false: NSS error code: -8018
[New Thread 0x7fff6989f700 (LWP 23956)]
[Thread 0x7fff6989f700 (LWP 23956) exited]
[New Thread 0x7fff6989f700 (LWP 23957)]
[New Thread 0x7fff68c9e700 (LWP 23958)]
[New Thread 0x7fff63fff700 (LWP 23959)]
[New Thread 0x7fff637fe700 (LWP 23960)]
[New Thread 0x7fff617fc700 (LWP 23961)]
[New Thread 0x7fff60ffb700 (LWP 23962)]
[New Thread 0x7fff607fa700 (LWP 23963)]
[New Thread 0x7fff5fff9700 (LWP 23964)]
[New Thread 0x7fff5f7f8700 (LWP 23965)]
[New Thread 0x7fff5eff7700 (LWP 23966)]
[New Thread 0x7fff5e7f6700 (LWP 23967)]
[New Thread 0x7fff5dff5700 (LWP 23968)]
[New Thread 0x7fff5d7f4700 (LWP 23969)]

Thread 1 "bn" received signal SIGSEGV, Segmentation fault.
[ Legend: Modified register | Code | Heap | Stack | String ]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
$rax   : 0x0               
$rbx   : 0x00000000044f6500  →  0x00000000044f6550  →  0x00007ffff2fceca0  →  0x0000000013787570  →  0x0000000039393834 ("4899"?)
$rcx   : 0x0               
$rdx   : 0x0               
$rsp   : 0x00007fffffffb5b0  →  0x00000000036759a0  →  0x0000000000000024 ("$"?)
$rbp   : 0x0000000001557850  →  0x00007ffff7663ba0  →  0x00007ffff60d28f0  →   mov rax, QWORD PTR [rdi+0x230]
$rsi   : 0x00000000044f70d2  →  "rameters"
$rdi   : 0x00007fffffffbc30  →  0x00007ffff7663740  →  0x00007ffff605ea70  →   push r15
$rip   : 0x00007ffff612b222  →   mov rax, QWORD PTR [rax+0x50]
$r8    : 0x00007fffffffa380  →  0x00007fffffff00ff  →  0x007fffffff01f000
$r9    : 0x00007fffd1aa1000  →  0x0000000000000063 ("c"?)
$r10   : 0x00007fffd0fd720c  →  <ffi_closure_unix64+178> mov rax, QWORD PTR [rsp-0x18]
$r11   : 0x00007fffd0fd71bc  →  0x0000004a0000003c ("<"?)
$r12   : 0x00007fffffffb7c0  →  0x00007fffffffb800  →  0x00007fffd08c6e00  →  0x00007fffd13fcea0  →  0x0000000000000002
$r13   : 0x00007fffffffb600  →  0x0000000001561580  →  0x00007ffff76659b0  →  0x00007ffff62a0df0  →   lea rax, [rip+0x13c4bb9]        # 0x7ffff76659b0
$r14   : 0x00007fffffffbc30  →  0x00007ffff7663740  →  0x00007ffff605ea70  →   push r15
$r15   : 0x00007fffffffb840  →  0x00007fff00000000
$eflags: [carry parity adjust zero sign trap INTERRUPT direction overflow RESUME virtualx86 identification]
$cs: 0x0033 $ss: 0x002b $ds: 0x0000 $es: 0x0000 $fs: 0x0000 $gs: 0x0000 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stack ────
0x00007fffffffb5b0│+0x0000: 0x00000000036759a0  →  0x0000000000000024 ("$"?)	 ← $rsp
0x00007fffffffb5b8│+0x0008: 0x00000000044f6500  →  0x00000000044f6550  →  0x00007ffff2fceca0  →  0x0000000013787570  →  0x0000000039393834 ("4899"?)
0x00007fffffffb5c0│+0x0010: 0x00007ffff69f5342  →  "old_type"
0x00007fffffffb5c8│+0x0018: 0x2b43811b00000020
0x00007fffffffb5d0│+0x0020: 0x00007fffffffbcd0  →  0x0000000000000004
0x00007fffffffb5d8│+0x0028: 0x0000000000000000
0x00007fffffffb5e0│+0x0030: 0x00007fffffffb630  →  0x00007ffff69f52a7  →  "new_ignore_disjoint_uses"
0x00007fffffffb5e8│+0x0038: 0x00007ffff644a467  →   test al, al
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
   0x7ffff612b206                  add    BYTE PTR [rcx+rcx*4-0x9], cl
   0x7ffff612b20a                  mov    QWORD PTR [rsp+0x138], 0x0
   0x7ffff612b216                  mov    QWORD PTR [rsp+0x140], 0x0
 → 0x7ffff612b222                  mov    rax, QWORD PTR [rax+0x50]
   0x7ffff612b226                  mov    rsi, QWORD PTR [rax+0x18]
   0x7ffff612b22a                  call   0x7ffff61d77c0
   0x7ffff612b22f                  lea    rsi, [rip+0x11a885f]        # 0x7ffff72d3a95
   0x7ffff612b236                  mov    rdi, rbx
   0x7ffff612b239                  call   0x7ffff643a590
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, Name: "bn", stopped, reason: SIGSEGV
[#1] Id 2, Name: "QXcbEventQueue", stopped, reason: SIGSEGV
[#2] Id 3, Name: "Qt bearer threa", stopped, reason: SIGSEGV
[#3] Id 4, Name: "QDBusConnection", stopped, reason: SIGSEGV
[#4] Id 5, Name: "sandbox_ipc_thr", stopped, reason: SIGSEGV
[#5] Id 6, Name: "bn", stopped, reason: SIGSEGV
[#6] Id 7, Name: "ThreadPoolServi", stopped, reason: SIGSEGV
[#7] Id 8, Name: "ThreadPoolForeg", stopped, reason: SIGSEGV
[#8] Id 9, Name: "Chrome_IOThread", stopped, reason: SIGSEGV
[#9] Id 10, Name: "ThreadPoolForeg", stopped, reason: SIGSEGV
[#10] Id 11, Name: "ThreadPoolForeg", stopped, reason: SIGSEGV
[#11] Id 12, Name: "inotify_reader", stopped, reason: SIGSEGV
[#12] Id 13, Name: "CompositorTileW", stopped, reason: SIGSEGV
[#13] Id 14, Name: "ThreadPoolForeg", stopped, reason: SIGSEGV
[#14] Id 15, Name: "Chrome_InProcGp", stopped, reason: SIGSEGV
[#15] Id 16, Name: "Chrome_ChildIOT", stopped, reason: SIGSEGV
[#16] Id 17, Name: "VideoCaptureThr", stopped, reason: SIGSEGV
[#17] Id 18, Name: "ThreadPoolForeg", stopped, reason: SIGSEGV
[#18] Id 19, Name: "ThreadPoolSingl", stopped, reason: SIGSEGV
[#19] Id 20, Name: "CacheThread_Blo", stopped, reason: SIGSEGV
[#20] Id 22, Name: "bn", stopped, reason: SIGSEGV
[#21] Id 23, Name: "VizCompositorTh", stopped, reason: SIGSEGV
[#22] Id 24, Name: "ThreadPoolSingl", stopped, reason: SIGSEGV
[#23] Id 26, Name: "bn", stopped, reason: SIGSEGV
[#24] Id 27, Name: "bn", stopped, reason: SIGSEGV
[#25] Id 28, Name: "bn", stopped, reason: SIGSEGV
[#26] Id 29, Name: "bn", stopped, reason: SIGSEGV
[#27] Id 30, Name: "bn", stopped, reason: SIGSEGV
[#28] Id 31, Name: "bn", stopped, reason: SIGSEGV
[#29] Id 32, Name: "bn", stopped, reason: SIGSEGV
[#30] Id 33, Name: "bn", stopped, reason: SIGSEGV
[#31] Id 34, Name: "bn", stopped, reason: SIGSEGV
[#32] Id 35, Name: "bn", stopped, reason: SIGSEGV
[#33] Id 36, Name: "bn", stopped, reason: SIGSEGV
[#34] Id 37, Name: "bn", stopped, reason: SIGSEGV
[#35] Id 38, Name: "bn", stopped, reason: SIGSEGV
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x7ffff612b222 → mov rax, QWORD PTR [rax+0x50]
[#1] 0x7ffff612c75e → lea rsi, [rip+0x8c8be6]        # 0x7ffff69f534b
[#2] 0x7ffff6063052 → mov rsi, QWORD PTR [rsp+0xa0]
[#3] 0x7ffff6059f2c → mov rdi, r14
[#4] 0x7ffff60562a7 → mov rax, QWORD PTR [rsp+0x20]
[#5] 0x7ffff6057ade → BNOpenExistingDatabaseWithProgress()
[#6] 0x4d45b1 → BinaryNinja::FileMetadata::OpenExistingDatabase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (unsigned long, unsigned long)> const&)()
[#7] 0x481e2f → MainWindow::openFilename(QString const&, bool)()
[#8] 0x48aac4 → NewTabWidget::recentFile(QString const&)()
[#9] 0x4ccc09 → NewTabWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)()
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
0x00007ffff612b222 in ?? () from /home/carl/binaryninja/libbinaryninjacore.so.1
```

```
gef➤  bt
#0  0x00007ffff612b222 in ?? () from /home/carl/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff612c75e in ?? () from /home/carl/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff6063052 in ?? () from /home/carl/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff6059f2c in ?? () from /home/carl/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff60562a7 in ?? () from /home/carl/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff6057ade in BNOpenExistingDatabaseWithProgress () from /home/carl/binaryninja/libbinaryninjacore.so.1
#6  0x00000000004d45b1 in BinaryNinja::FileMetadata::OpenExistingDatabase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (unsigned long, unsigned long)> const&) ()
#7  0x0000000000481e2f in MainWindow::openFilename(QString const&, bool) ()
#8  0x000000000048aac4 in NewTabWidget::recentFile(QString const&) ()
#9  0x00000000004ccc09 in NewTabWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#10 0x00007ffff3a1a33f in void doActivate<false>(QObject*, int, void**) () from /home/carl/binaryninja/libQt5Core.so.5
#11 0x00007ffff54c16e2 in QLabel::linkActivated(QString const&) () from /home/carl/binaryninja/libQt5Widgets.so.5
#12 0x00007ffff54c51f9 in QLabel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /home/carl/binaryninja/libQt5Widgets.so.5
#13 0x00007ffff3a1a33f in void doActivate<false>(QObject*, int, void**) () from /home/carl/binaryninja/libQt5Core.so.5
#14 0x00007ffff55661f5 in QWidgetTextControl::linkActivated(QString const&) () from /home/carl/binaryninja/libQt5Widgets.so.5
#15 0x00007ffff556becc in QWidgetTextControlPrivate::activateLinkUnderCursor(QString) () from /home/carl/binaryninja/libQt5Widgets.so.5
#16 0x00007ffff556cddb in QWidgetTextControlPrivate::mouseReleaseEvent(QEvent*, Qt::MouseButton, QPointF const&, QFlags<Qt::KeyboardModifier>, QFlags<Qt::MouseButton>, QPoint const&) () from /home/carl/binaryninja/libQt5Widgets.so.5
#17 0x00007ffff5571046 in QWidgetTextControl::processEvent(QEvent*, QMatrix const&, QWidget*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#18 0x00007ffff556826b in QWidgetTextControl::processEvent(QEvent*, QPointF const&, QWidget*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#19 0x00007ffff54c32e8 in QLabelPrivate::sendControlEvent(QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#20 0x00007ffff53d5728 in QWidget::event(QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#21 0x00007ffff547d84e in QFrame::event(QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#22 0x00007ffff5396a7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#23 0x00007ffff539e208 in QApplication::notify(QObject*, QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#24 0x00007ffff39e3ae8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/carl/binaryninja/libQt5Core.so.5
#25 0x00007ffff539d1fa in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /home/carl/binaryninja/libQt5Widgets.so.5
#26 0x00007ffff53eee41 in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#27 0x00007ffff53f1a8b in QWidgetWindow::event(QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#28 0x00007ffff5396a7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#29 0x00007ffff539dcb0 in QApplication::notify(QObject*, QEvent*) () from /home/carl/binaryninja/libQt5Widgets.so.5
#30 0x00007ffff39e3ae8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/carl/binaryninja/libQt5Core.so.5
#31 0x00007ffff4a8bad8 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /home/carl/binaryninja/libQt5Gui.so.5
#32 0x00007ffff4a8cfb5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/carl/binaryninja/libQt5Gui.so.5
#33 0x00007ffff4a69bdb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/carl/binaryninja/libQt5Gui.so.5
#34 0x00007fffe1cdde7a in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /home/carl/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#35 0x00007fffe774b7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fffe774ba60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fffe774bb0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff3a3c55c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/carl/binaryninja/libQt5Core.so.5
#39 0x00007ffff39e2502 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/carl/binaryninja/libQt5Core.so.5
#40 0x00007ffff39eb430 in QCoreApplication::exec() () from /home/carl/binaryninja/libQt5Core.so.5
#41 0x0000000000454260 in main ()
```

**Comment by negasora** [comment]
Fixed in 1.3.2031-dev
