### ISSUE TITLE
HLIL_BLOCK.il_basic_block() crashes

### ISSUE THREAD

**Issue by ejm9** [Vector35/binaryninja-api#2018]
Using the API (not GUI) on latest dev branch 2.1.2448-dev, Most HLIL instructions (binaryninja.highlevelil.HighLevelILInstruction) work fine if you access hlil..il_basic_block, but if the hlil is of type operation == HLIL_BLOCK, then it crashes as shown below.  

>>> instr.operands[1].il_basic_block
Exception ignored in: <function BasicBlock.__del__ at 0x7f7e5012c940>
Traceback (most recent call last):
  File "/home/user/binaryninja/python/binaryninja/basicblock.py", line 121, in __del__
    core.BNFreeBasicBlock(self.handle)
AttributeError: 'HighLevelILBasicBlock' object has no attribute 'handle'
Traceback (most recent call last):
  File "/home/user/n/pycharm-community-2020.1.1/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/user/binaryninja/python/binaryninja/highlevelil.py", line 547, in il_basic_block
    return HighLevelILBasicBlock(self._function.source_function.view, core.BNGetHighLevelILBasicBlockForInstruction(self._function.handle, self._instr_index), self._function)
  File "/home/user/binaryninja/python/binaryninja/highlevelil.py", line 939, in __init__
    super(HighLevelILBasicBlock, self).__init__(handle, view)
  File "/home/user/binaryninja/python/binaryninja/basicblock.py", line 114, in __init__
    self.handle = core.handle_of_type(handle, core.BNBasicBlock)
  File "/home/user/binaryninja/python/binaryninja/_binaryninjacore.py", line 17319, in handle_of_type
    raise ValueError('expected pointer to %s' % str(handle_type))
ValueError: expected pointer to <class 'binaryninja._binaryninjacore.BNBasicBlock'>

**Comment by D0ntPanic** [comment]
Fixed in 2481. Note that `HLIL_BLOCK` returns `None` for the `il_basic_block`. This is intentional, as an `HLIL_BLOCK` can belong to multiple basic blocks. The `body` member can be used to get the instructions contained within it.
