### ISSUE TITLE
Windows - Crash in template_simplifier\src\simplifier.rs:890:21

### ISSUE THREAD

**Issue by marpie** [Vector35/binaryninja-api#2244]
Loading the attached file triggers the followng crash:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\jenkins\workspace\binaryninja-dev\os\win64\core\rust_modules\template_simplifier\src\simplifier.rs:890:21
```

Trigger-File: [string-test.zip](https://github.com/Vector35/binaryninja-api/files/5862566/string-test.zip)

Loading the file in the GUI results in a crash, using headless the stacktrace can be captured.

Version Info:

Binary Ninja Version: 2.2.2613-dev,  1ee6108
Platform: Windows 10 Version 2009

## Stacktrace

Running headless the following stacktrace can be produced by setting `RUST_BACKTRACE=full`:

```
python batch_process-marpie.py string-test.o
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\jenkins\workspace\binaryninja-dev\os\win64\core\rust_modules\template_simplifier\src\simplifier.rs:890:21
stack backtrace:
   0:     0x7fff0793f9d9 - <unknown>
   1:     0x7fff0794b95b - BNGetDataBufferContents
   2:     0x7fff0793bb28 - <unknown>
   3:     0x7fff07942074 - <unknown>
   4:     0x7fff07941c58 - <unknown>
   5:     0x7fff0794292f - <unknown>
   6:     0x7fff07942495 - <unknown>
   7:     0x7fff079402bf - <unknown>
   8:     0x7fff07942449 - <unknown>
   9:     0x7fff0794abf0 - BNGetDataBufferContents
  10:     0x7fff0794abb7 - BNGetDataBufferContents
  11:     0x7fff07961d10 - BNGetDataBufferLength
  12:     0x7fff0796160d - BNGetDataBufferLength
  13:     0x7fff0796182b - BNGetDataBufferLength
  14:     0x7fff0795b4c9 - BNGetDataBufferLength
  15:     0x7fff07961e4c - BNGetDataBufferLength
  16:     0x7fff07935f38 - <unknown>
  17:     0x7fff07d6974c - BNGetReportView
  18:     0x7fff07af0789 - BNDemangleMSWithOptions
  19:     0x7fff07aeff94 - BNDemangleMSWithOptions
  20:     0x7fff07b1072c - BNWriteDataForDownloadInstance
  21:     0x7fff07b16168 - BNWriteDataForDownloadInstance
  22:     0x7fff07aad59b - BNCreateBinaryViewOfType
  23:     0x7fff46414461 - ffi_prep_go_closure
  24:     0x7fff4641418d - ffi_call_go
  25:     0x7fff46414042 - ffi_call
  26:     0x7fff3c372cc5 - <unknown>
  27:     0x7fff3c372a27 - <unknown>
  28:     0x7fff3c37267c - <unknown>
  29:     0x7fff0d3bd58b - PyObject_Call
  30:     0x7fff0d39146e - PyEval_EvalFrameDefault
  31:     0x7fff0d3882f3 - PyObject_GC_Del
  32:     0x7fff0d389f37 - PyFunction_Vectorcall
  33:     0x7fff0d38d038 - PyEval_EvalFrameDefault
  34:     0x7fff0d38cf5a - PyEval_EvalFrameDefault
  35:     0x7fff0d3882f3 - PyObject_GC_Del
  36:     0x7fff0d38e2d6 - PyEval_EvalFrameDefault
  37:     0x7fff0d38d638 - PyEval_EvalFrameDefault
  38:     0x7fff0d3882f3 - PyObject_GC_Del
  39:     0x7fff0d4023b5 - PyEval_EvalCodeWithName
  40:     0x7fff0d4022f7 - PyEval_EvalCodeEx
  41:     0x7fff0d402255 - PyEval_EvalCode
  42:     0x7fff0d451c5a - PyCodec_EncodeText
  43:     0x7fff0d451bda - PyCodec_EncodeText
  44:     0x7fff0d3aaeec - PyRun_FileExFlags
  45:     0x7fff0d3a927b - PyRun_SimpleFileExFlags
  46:     0x7fff0d4d19dc - PyRun_AnyFileExFlags
  47:     0x7fff0d3ab672 - PyList_GetItem
  48:     0x7fff0d3ac7ec - Py_RunMain
  49:     0x7fff0d3ac675 - Py_RunMain
  50:     0x7fff0d3ac551 - Py_Main
  51:     0x7ff634681258 - <unknown>
  52:     0x7fff54e97034 - BaseThreadInitThunk
  53:     0x7fff5517d0d1 - RtlUserThreadStart
fatal runtime error: Rust panics must be rethrown
```

**Comment by KyleMiles** [comment]
Thanks for the bug report!  The bug is fixed, and I extended the simplifier to accommodate the symbols you're working with in 2.2.2626-dev.
