### ISSUE TITLE
Issue with recognizing arguments passed through stack for function call (x86_64 sysv)

### ISSUE THREAD

**Issue by renorobert** [Vector35/binaryninja-api#2463]
There seems to be an issue with recognizing the arguments when they are passed in stack (x86_64 sysv calling convention). If any argument prior to the argument passed in stack is not used within the function, then the argument seems to be left out from type info and parameter list. 

```
int test1(int a1, int a2, int a3, int a4, int a5, int a6, int a7)       // a1 - a6 unused, a7 in stack
{
        return a7;
}

int test2(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8) // a7 in stack is unused
{
        return a1 + a2 + a3 + a4 + a5 + a6 + a8;
}

int test3(int a1, int a2, int a3, int a4, int a5, int a6)       // a1 - a5 unused, but works fine
{
        return a6;
}

```
Type info of test1 - (arg7 is labelled as arg1)

```
>>> function = bv.get_function_at(here)
>>> function.name
'test1'
>>> function.parameter_vars
[<var int32_t arg1>]
>>> function.function_type
<type: uint64_t (int32_t arg1)>
```

Type info of test2 - (arg8 is labelled as arg7)

```
>>> function = bv.get_function_at(here)
>>> function.name
'test2'
>>> function.parameter_vars
[<var int32_t arg1>, <var int32_t arg2>, <var int32_t arg3>, <var int32_t arg4>, <var int32_t arg5>, <var int32_t arg6>, <var int32_t arg7>]
>>> function.function_type
<type: uint64_t (int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6, int32_t arg7)>
```

Type info of test3 - works fine
```
>>> function = bv.get_function_at(here)
>>> function.name
'test3'
>>> function.parameter_vars
[<var int32_t arg1>, <var int32_t arg2>, <var int32_t arg3>, <var int32_t arg4>, <var int32_t arg5>, <var int32_t arg6>]
>>> function.function_type
<type: uint64_t (int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6)>
```

**Comment by renorobert** [comment]
This could be a similar problem. Here a function has a parameter variable’s (arg1) type information but name is missing. arg1 is unused in this case. current_function.parameter_vars is throwing error and breaking analysis. I think, even if its unused, argument variables should be declared

```
ffffffff80a9cca0  int64_t ksched_get_priority_max(int64_t, int32_t arg2, int32_t* arg3)

int64_t __saved_rbp  {Frame offset -8}
void* const __return_addr  {Frame offset 0}
int32_t* arg3  {Register rdx}
int32_t arg2  {Register rsi}

ffffffff80a9cca0  ksched_get_priority_max:
ffffffff80a9cca0  83c6ff             add     esi, 0xffffffff
ffffffff80a9cca3  b816000000         mov     eax, 0x16
ffffffff80a9cca8  83fe02             cmp     esi, 0x2
ffffffff80a9ccab  7713               ja      0xffffffff80a9ccc0

ffffffff80a9ccad  55                 push    rbp {__saved_rbp}
ffffffff80a9ccae  4889e5             mov     rbp, rsp {__saved_rbp}
ffffffff80a9ccb1  4863c6             movsxd  rax, esi
ffffffff80a9ccb4  8b048560f94e81     mov     eax, dword [rax*4-0x7eb106a0]
ffffffff80a9ccbb  8902               mov     dword [rdx], eax
ffffffff80a9ccbd  31c0               xor     eax, eax  {0x0}
ffffffff80a9ccbf  5d                 pop     rbp {__saved_rbp}

ffffffff80a9ccc0  c3                 retn     {__return_addr}

>>> current_function.vars
[<var int64_t __saved_rbp>, <var void* const __return_addr>, <var int64_t rax>, <var int64_t rax_1>, <var int32_t rax_2>, <var int32_t* arg3>, <var int32_t arg2>, <var int32_t rsi>]

>>> current_function.parameter_vars
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "***/python/binaryninja/function.py", line 1026, in __repr__
    return repr(self._vars)
  File "***/python/binaryninja/function.py", line 830, in __repr__
    return "<var %s %s%s>" % (self.type.get_string_before_name(), self.name, self.type.get_string_after_name())
AttributeError: 'NoneType' object has no attribute 'get_string_before_name'
```

https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/sys/kern/ksched.c#L226

Version 2.4.2846

**Comment by renorobert** [comment]
Could be related to https://github.com/Vector35/binaryninja-api/issues/2566
