### ISSUE TITLE
`Architecture.perform_assemble` is broken

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2525]
Binary Ninja 2.4.2871

```
>>> bv.arch.can_assemble
True
>>> bv.arch.perform_assemble("xor eax, eax; ret;", ref.function.start)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/architecture.py", line 1311, in perform_assemble
    raise NotImplementedError("Architecture does not implement an assembler.\n")
NotImplementedError: Architecture does not implement an assembler.
```

Occurs on both x86_64 and ARM, probably a Python bindings issue.

**Comment by jonpalmisc** [comment]
Turns out you're supposed to use `assemble()` and not `perform_assemble()`.
