### ISSUE TITLE
Typo `in` should be `if` in binaryview.get_functions_containing causes NameError

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#2536]
**Binary Ninja Version**
dev branch of binaryninja-api

**Describe the bug**
Typo, `in` should be `if` since this commit:
 https://github.com/Vector35/binaryninja-api/commit/d9b1df165f9daad6a5229718ecd0ee50a5ef6bf1#diff-0f09d81e331a0fa711c6be24e48dead7c1c6dc7eb1fc415d1d86e1265eb8a531R3224

**To Reproduce**
1. Open a bndb
2. Go to python console, invoke `bv.get_functions_containing` with a value for the `plat` argument.
3. See error in python console:
```
>>> bv.get_functions_containing(here, Platform['windows-thumb2'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/binaryninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 3240, in get_functions_containing
    result = [func for func in result in func.platform == plat]
NameError: name 'func' is not defined
```

**Expected behavior**
It should not throw an error.

**Version and Platform (required):**
 - Binary Ninja: since this commit:
 https://github.com/Vector35/binaryninja-api/commit/d9b1df165f9daad6a5229718ecd0ee50a5ef6bf1

**Comment by galenbwill** [comment]
Fixed with this commit: https://github.com/Vector35/binaryninja-api/commit/3e2288bba38147509808b29ae60720627dc9bb03
