### ISSUE TITLE
Python architecture intrinsics fail on new api

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2635]
**Binary Ninja Version**
2.4.2981-dev

**Describe the bug**
When a python Architecture with custom intrinsics tries to call register(), an exception is raised and the arch fails to load.

**To Reproduce**
```py
from binaryninja import Architecture, IntrinsicInfo, IntrinsicInput, Type


class TestArch(Architecture):
    name = "Test"
    intrinsics = {
        "test": IntrinsicInfo([IntrinsicInput(Type.int(4), "value")], [Type.float(4)]),
    }


TestArch.register()
```

1. Copy this code into a python file in plugins
2. Launch binary ninja

**Expected behavior**
I expected the register() to succeed and not raise any errors.

**Error log**
```
Traceback (most recent call last):
  File "/Users/glennsmith/Library/Application Support/Binary Ninja/plugins/test_arch.py", line 14, in <module>
    TestArch.register()
  File "/Users/glennsmith/Documents/binaryninja/build_qt6/out/binaryninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/architecture.py", line 495, in register
    arch = cls()
  File "/Users/glennsmith/Documents/binaryninja/build_qt6/out/binaryninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/architecture.py", line 460, in __init__
    info.index = intrinsic_index
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'index'
Python plugin 'test_arch' could not be loaded
```

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2981-dev
 - OS: macOS
 - Version 10.15.7

**Comment by plafosse** [comment]
This is now fixed somewhere < 2.4.2998
