### ISSUE TITLE
`TypeError` in `get_all_user_var_values`

### ISSUE THREAD

**Issue by mrphrazer** [Vector35/binaryninja-api#2934]
Version `3.0.3247-dev` throws a type error for `get_all_user_var_values`:
```
>>> current_function.get_all_user_var_values()
{}
>>> current_function.set_user_var_value(current_mlil[0].operands[0], current_address, PossibleValueSet.constant(0))
>>> current_function.get_all_user_var_values()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<redacted>/python/binaryninja/function.py", line 3027, in get_all_user_var_values
    result[var][def_site] = variable.PossibleValueSet(def_site.arch, var_val.value)
  File "<string>", line 3, in __hash__
TypeError: unhashable type
```

**Comment by plafosse** [comment]
Thanks for the report. Fixed in 3.0.3311
