### ISSUE TITLE
ELF file crashes binaryninja

### ISSUE THREAD

**Issue by ekse** [Vector35/binaryninja-api#328]
I was bored this weekend and did a bit of fuzzing. The following ELF file crashes BinaryNinja when opened.

Test Build: 1.0.297
Crash file:
https://drive.google.com/open?id=0B9u4BZE06xNIRmU0d1Z4UlRLRGc

Console output:
```
terminate called after throwing an instance of 'BinaryNinjaCore::ReadException'
  what():  read out of bounds
fish: “./binaryninja” terminated by signal SIGABRT (Abort)
```

backtrace:
```
#0  0x00007ffff526f418 in __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff527101a in __GI_abort () at abort.c:89
#2  0x00007ffff5bb184d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5baf6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5baf701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5baf919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff79cf635 in ?? () from /home/ekse/tools/BinaryNinja/binaryninja/libbinaryninjacore.so.1
#7  0x00007ffff79cf76d in ?? () from /home/ekse/tools/BinaryNinja/binaryninja/libbinaryninjacore.so.1
#8  0x00007ffff79c451d in ?? () from /home/ekse/tools/BinaryNinja/binaryninja/libbinaryninjacore.so.1
#9  0x00007ffff79d08ed in BNCreateBinaryViewOfType ()
   from /home/ekse/tools/BinaryNinja/binaryninja/libbinaryninjacore.so.1
#10 0x00000000004c2a73 in BinaryNinja::CoreBinaryViewType::Create(BinaryNinja::BinaryView*) ()
#11 0x000000000044eb50 in FileContext::getDataView(QString const&) ()
#12 0x000000000044f084 in FileContext::getBestType() ()
#13 0x000000000042ba97 in MainWindow::createTab(FileContext*, QString const&, bool) ()
#14 0x000000000043301b in MainWindow::openFilename(QString const&) ()
#15 0x0000000000433749 in MainWindow::open() ()
```

**Comment by ekse** [comment]
This is handled correctly in 1.0.307.

**Comment by psifertex** [comment]
Yay! Thanks for the report. :-)
