### ISSUE TITLE
Invalid ELF file crashes binary ninja

### ISSUE THREAD

**Issue by ZetaTwo** [Vector35/binaryninja-api#350]
I have a file which is actually not a valid ELF file which crashes binary ninja. I don't really know where it came from but either way, I guess that an invalid binary should preferrably cause an error message, not a crash.

Test Build: 1.0.297
Crash file: https://dl.dropboxusercontent.com/u/14098192/crash1.bin

Console output:
```
./binaryninja/binaryninja
terminate called after throwing an instance of 'BinaryNinjaCore::ReadException'
  what():  read out of bounds
[1]    24503 abort (core dumped)  ./binaryninja/binaryninja
```

Backtrace:

```
#0  0x00007ffff526f418 in __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff527101a in __GI_abort () at abort.c:89
#2  0x00007ffff5bb184d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5baf6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5baf701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5baf919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff79cf635 in ?? () from /home/zetatwo/tools/binaryninja/libbinaryninjacore.so.1
#7  0x00007ffff79cf7b5 in ?? () from /home/zetatwo/tools/binaryninja/libbinaryninjacore.so.1
#8  0x00007ffff79c3d21 in ?? () from /home/zetatwo/tools/binaryninja/libbinaryninjacore.so.1
#9  0x00007ffff79d08ed in BNCreateBinaryViewOfType () from /home/zetatwo/tools/binaryninja/libbinaryninjacore.so.1
#10 0x00000000004c2a73 in BinaryNinja::CoreBinaryViewType::Create(BinaryNinja::BinaryView*) ()
#11 0x000000000044eb50 in FileContext::getDataView(QString const&) ()
#12 0x000000000044f084 in FileContext::getBestType() ()
#13 0x000000000042ba97 in MainWindow::createTab(FileContext*, QString const&, bool) ()
#14 0x000000000043301b in MainWindow::openFilename(QString const&) ()
#15 0x0000000000433749 in MainWindow::open() ()
#16 0x00007ffff6138cef in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/zetatwo/tools/binaryninja/libQt5Core.so.5
#17 0x00007ffff75db4d2 in QAbstractButton::clicked(bool) () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#18 0x00007ffff73588c5 in ?? () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#19 0x00007ffff7359624 in ?? () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#20 0x00007ffff73597c4 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#21 0x00007ffff72a4308 in QWidget::event(QEvent*) () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#22 0x00007ffff726204c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#23 0x00007ffff7266f0e in QApplication::notify(QObject*, QEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#24 0x00007ffff610fe80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Core.so.5
#25 0x00007ffff7265a33 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#26 0x00007ffff72bf5da in ?? () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#27 0x00007ffff72c16db in ?? () from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#28 0x00007ffff726204c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#29 0x00007ffff7266488 in QApplication::notify(QObject*, QEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Widgets.so.5
#30 0x00007ffff610fe80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Core.so.5
#31 0x00007ffff6a0e97b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /home/zetatwo/tools/binaryninja/libQt5Gui.so.5
#32 0x00007ffff6a10485 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/zetatwo/tools/binaryninja/libQt5Gui.so.5
#33 0x00007ffff69f16a3 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/zetatwo/tools/binaryninja/libQt5Gui.so.5
#34 0x00007fffe8c05720 in ?? () from /home/zetatwo/tools/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#35 0x00007ffff448a1a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff448a400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff448a4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff615f4e7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/zetatwo/tools/binaryninja/libQt5Core.so.5
#39 0x00007ffff610defa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/zetatwo/tools/binaryninja/libQt5Core.so.5
#40 0x00007ffff6115d9d in QCoreApplication::exec() () from /home/zetatwo/tools/binaryninja/libQt5Core.so.5
#41 0x00000000004284da in main ()
#42 0x00007ffff525a830 in __libc_start_main (main=0x4273a0 <main>, argc=0x1, argv=0x7fffffffe108, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe0f8)
    at ../csu/libc-start.c:291
#43 0x0000000000429145 in _start ()
```

**Comment by D0ntPanic** [comment]
Fixed in dev
