### ISSUE TITLE
Crash on trying to analyse m68k binary after update

### ISSUE THREAD

**Issue by dragonmux** [Vector35/binaryninja-api#3715]
We can consistently crash Binary Ninja on starting the analysis of a m68k binary (using the Motorola 68k Architecture Plugin by Galen Williamson) having just updated from the previous release. Attaching GDB and inspecting state, we see the following stack trace indicating a bug in Binja itself, and the program closes with SIGSEGV:

```
Thread 34 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6904d700 (LWP 349454)]
0x00007fffee68924d in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
sora:/home/dx-mon:gdb-34@None> bt
#0  0x00007fffee68924d in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#1  0x00007fffee3caf6e in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#2  0x00007fffee017acf in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#3  0x00007fffee044eb5 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#4  0x00007fffee04d87e in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#5  0x00007fffee5e4494 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#6  0x00007fffee6d3221 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
#7  0x00007ffff6d01ed0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7e01ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007fffebb27a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Binary Ninja Version: 3.2.3898 Personal, 16354a74
Platform: Debian GNU/Linux 11 (bullseye)

A listing of threads that were running is available on request (there are 40 so it's quite long).

**Comment by rssor** [comment]
This is quite probably due to a change I made last week, I'll try to get the possible fix pushed ASAP.

**Comment by psifertex** [comment]
Builds >= 3899 contain that fix and appear to be working correctly. I tested on https://github.com/radareorg/radare2-testbins/blob/master/elf/analysis/busybox.m68k which was crashing on 3898 with that plugin. 

If you're still experiencing a crash, let us know!

**Comment by dragonmux** [comment]
Confirmed, just updated and Binjary Ninja no longer crashes when working with m68k binaries. Many thanks for the quick turnaround!
