### ISSUE TITLE
Error loading nes.py plugin

### ISSUE THREAD

**Issue by sboesen** [Vector35/binaryninja-api#382]
When I load a rom into the `nes.py` plugin in binary ninja `1.0.307` build `f2ac3d81` on OS X `10.11.6` I get this error:
```
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/__init__.py", line 883, in _is_valid_for_data
    return cls.is_valid_for_data(BinaryView(None, handle = core.BNNewViewReference(data)))
  File "/Users/stefan/Library/Application Support/Binary Ninja/plugins/nes.py", line 529, in is_valid_for_data
    hdr = data.read(0, 16)
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/__init__.py", line 1574, in read
    buf = DataBuffer(handle = core.BNReadViewBuffer(self.handle, offset, length))
NameError: global name 'offset' is not defined
```
This error doesn't appear to be coming from the plugin code, but from within binary ninja D:

**Comment by psifertex** [comment]
Sorry about that, some last-minute changes to the Python API documentation caused trouble. We're planning on pushing an update to fix it -- in the meantime, you can pull the latest version manually from here and update and it should work fine: https://github.com/Vector35/binaryninja-api/tree/dev/python

The only thing you need to download is the `__init__.py` and replace the version in the install path of your copy of binary ninja. When it auto-update to the newest version it will automatically put the latest in place and shouldn't cause any problems.
