### ISSUE TITLE
`DataVariable` won't let you access array members of a `struct`

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3842]
**Version and Platform (required):**
- Binary Ninja Version: 3.3.4013-dev
- OS: macOS
- OS Version: 13.1
- CPU Architecture: arm64

**Bug Description:**
After creating a `struct` and applying it to a type as an array, sometimes you will wind up with the following error when trying to access `var[1]`:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja Enterprise.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 9137, in __getitem__
    return self._sdv[item]
           ~~~~~~~~~^^^^^^
  File "/Applications/Binary Ninja Enterprise.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 8949, in __getitem__
    raise ValueError("Can't get member of non-structure")
ValueError: Can't get member of non-structure
```

...despite the fact that the `DataVariable` _should_ be a `struct`.

**Steps To Reproduce:**

1. Create a `struct` like this:

```
struct Foo __packed
{
    uint32_t field_0;
    void* field_4;
};
```

2. Do the following:

```
>>> var = bv.get_data_var_at(0x100007ade)
>>> foo_type = bv.get_type_by_name('Foo')
>>> var.type = ArrayType.create(foo_type, 4)
>>> var.type
<type: immutable:ArrayTypeClass 'struct Foo[0x4]'>
>>> type(var)
<class 'binaryninja.binaryview.DataVariable'>
>>> type(var[1])
```

3. Observe that the error matches what I showed above

**Expected Behavior:**

If, instead, you have a struct that looks like this:

```
struct Bar __packed
{
    char thing;
};
```

...everything will work just fine:

```
>>> var = bv.get_data_var_at(0x100007ade)
>>> bar_type = bv.get_type_by_name('Bar')
>>> var.type = ArrayType.create(bar_type, 4)
>>> var.type
<type: immutable:ArrayTypeClass 'struct Bar[0x4]'>
>>> type(var)
<class 'binaryninja.binaryview.DataVariable'>
>>> type(var[1])
<class 'binaryninja.binaryview.TypedDataAccessor'>
```

**Comment by fuzyll** [comment]
I believe this to be fixed in builds >= 4051.
