### ISSUE TITLE
binaryninja.load() with bytes argument is broken

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#4477]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4380

**Bug Description:**
```
Traceback (most recent call last):
  File "/Users/cynder/src/macho-mutate/main.py", line 68, in <module>
    main()
  File "/Users/cynder/src/macho-mutate/main.py", line 64, in main
    load(bytes(mutated_binary.read()))
  File "/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/__init__.py", line 334, in load
    bv = BinaryView.load(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/binaryview.py", line 2140, in load
    handle = core.BNLoadBinaryView(raw_view.handle, update_analysis, progress_cfunc, metadata.Metadata(options).handle)
TypeError: BNLoadBinaryView() missing 1 required positional argument: 'isDatabase'
```

**Steps To Reproduce:**
Copy pasted from our official docs for this function:
```
with load(bytes.fromhex('5054ebfe'), options={'loader.architecture' : 'x86'}) as bv:
    print(len(list(bv.functions)))
```

**Comment by cxnder** [comment]
Resolved in **dev builds >= 3.5.4385**
