### ISSUE TITLE
DebugInfo.parsers API is broken

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#4652]
**Version and Platform (required):**
- Binary Ninja Version: 3.6 - dev

```
>>> bv.debug_info.parsers
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/peterlafosse/src/binaryninja/build_release_test_typelibupdate/out/binaryninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/debuginfo.py", line 303, in parsers
    result.append(parsers[i].encode("utf-8"))
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by plafosse** [comment]
Yes that would fix this please merge it.
