### ISSUE TITLE
TypeError in Function.get_low_level_il_at

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4660]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4556-dev Personal (dd5c4859)
- OS: Arch Linux x86_64
- OS Version:  kernel 6.4.9-zen1-1-zen
- CPU Architecture: x86_64

**Bug Description:**
While accessing the mlil property of a ReferenceSource (from one of a function's caller_sites) using the Sidekick plugin, the following Python traceback occurs:

```
[Default] Traceback (most recent call last):
[Default] File "/home/masterr3c0rd/.binaryninja/repositories/Sidekick/plugins/Vector35_Sidekick/suggestions/suggestion_classes.py", line 831, in apply
[Default] operations, ip_pts = extract_operations(bv, scope)
[Default] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Default] File "/home/masterr3c0rd/.binaryninja/repositories/Sidekick/plugins/Vector35_Sidekick/code_analysis/memory_operations.py", line 809, in extract_operations
[Default] allocators = {alloc_func.start: alloc_func for alloc_func in find_allocators(bv)}
[Default] ^^^^^^^^^^^^^^^^^^^
[Default] File "/home/masterr3c0rd/.binaryninja/repositories/Sidekick/plugins/Vector35_Sidekick/code_analysis/allocators.py", line 105, in find_allocators
[Default] insn = xref.mlil
[Default] ^^^^^^^^^
[Default] File "/home/masterr3c0rd/binaryninja/plugins/../python/binaryninja/binaryview.py", line 124, in mlil
[Default] llil = self.llil
[Default] ^^^^^^^^^
[Default] File "/home/masterr3c0rd/binaryninja/plugins/../python/binaryninja/binaryview.py", line 119, in llil
[Default] return self.function.get_low_level_il_at(self.address, self.arch)
[Default] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Default] File "/home/masterr3c0rd/binaryninja/plugins/../python/binaryninja/function.py", line 2077, in get_low_level_il_at
[Default] if idx == len(self.llil):
[Default] ^^^^^^^^^^^^^^
[Default] TypeError: object of type 'NoneType' has no len()
[Sidekick] Failed to extract operations: object of type 'NoneType' has no len()

```

**Steps To Reproduce:**
This error was encountered by one of our Sidekick external testers, who is unable to share the binary.

**Comment by plafosse** [comment]
I believe this is fixed now. If this same situation occurs an exception should be thrown that can be caught instead of an unrecoverable internal error.
