### ISSUE TITLE
connect_vscode_debugger broken with default python

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4663]
The API only works right now with a third-party python selected in settings.

**Comment by psifertex** [comment]
Results in an error of:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja-dev.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/__init__.py", line 376, in connect_vscode_debugger
    debugpy.listen(("127.0.0.1", port))
  File "/Users/jwiens/Library/Application Support/Binary Ninja/python310/site-packages/debugpy/public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/jwiens/Library/Application Support/Binary Ninja/python310/site-packages/debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/Users/jwiens/Library/Application Support/Binary Ninja/python310/site-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/Users/jwiens/Library/Application Support/Binary Ninja/python310/site-packages/debugpy/server/api.py", line 234, in listen
    raise RuntimeError("error spawning debug adapter: " + str(exc))
RuntimeError: error spawning debug adapter: [Errno 2] No such file or directory: '/Applications/Binary Ninja-dev.app/Contents/MacOS/plugins/../../Resources/bundled-python3/bin/python3'
```

**Comment by plafosse** [comment]
This line  https://github.com/Vector35/binaryninja-api/blob/dev/python/__init__.py#L375
needs to be updated with the following path:

./Contents/Frameworks/Python.framework/Versions/3.10/bin/python3.10

**Comment by kristopax** [comment]
This line needs to have that new path added: https://github.com/Vector35/binaryninja-api/blob/dev/python/__init__.py#L375:

`./Contents/Frameworks/Python.framework/Versions/3.10/bin/python3.10`


Don't remove the one that's there just check if it doesn't exist and try the alternate path that's correct for the bundled one instead.
