### ISSUE TITLE
Python Type Container init fails, uses deprecated type initialization method

### ISSUE THREAD

**Issue by 0cyn** [Vector35/binaryninja-api#4816]
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4654
- OS: macOS
- CPU Architecture: M1

**Steps To Reproduce:**

Paste `Platform['mac-aarch64'].type_container.types` in console, hit enter. 

```
>>> Platform['mac-aarch64'].type_container.types
Exception ignored in: <function Type.__del__ at 0x116c88dc0>
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/types.py", line 1785, in __del__
    core.BNFreeType(self._handle)
AttributeError: 'Type' object has no attribute '_handle'
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/typecontainer.py", line 221, in types
    type = ty_.Type(handle=core.BNNewTypeReference(result_types[i]))
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/types.py", line 1765, in __init__
    raise Exception("Cannot instantiate Type directly use Type.create instead")
Exception: Cannot instantiate Type directly use Type.create instead
```

**Comment by plafosse** [comment]
Fixed in 3.6.4719
