### ISSUE TITLE
Issues with pydevd modules and pycharm remote debugger

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#4904]
### Discussed in https://github.com/Vector35/binaryninja-api/discussions/4836

<div type='discussions-op-text'>

<sup>Originally posted by **N0K0** December 18, 2023</sup>
Hi! I have some issues getting the remote debugger up and running. This is a clean Win10 vm with Binja Personal and PyCharm Pro. Clean venv with python3.10

Issue at hand:

```bash
[Default] Traceback (most recent call last):
[Default]   File "C:\Users\n\AppData\Roaming\Binary Ninja\plugins\decrypt_string\__init__.py", line 9, in <module>
[Default]     connect_pycharm_debugger()
[Default]   File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\__init__.py", line 356, in connect_pycharm_debugger
[Default]     import pydevd_pycharm  # type: ignore
[Default]   File "C:\Users\n\AppData\Roaming\Binary Ninja\python310\site-packages\pydevd_pycharm.py", line 3, in <module>
[Default]     from pydevd import settrace
[Default]   File "C:\Users\n\AppData\Roaming\Binary Ninja\python310\site-packages\pydevd.py", line 16, in <module>
[Default]     from _pydevd_bundle.pydevd_collect_try_except_info import collect_return_info
[Default] ModuleNotFoundError: No module named '_pydevd_bundle.pydevd_collect_try_except_info'
[PythonPlugin] Python plugin 'decrypt_string' could not be loaded
```

Plugin:

```python
from binaryninja import *

from binaryninja.log import log_info


import sys
print(sys.path)

connect_pycharm_debugger()

class DecodeString(binaryninja.Transform):
    name = "Decode String"
    description = "Decode String"
    input_type = "Raw"
    output_type = "Raw"
    transform_type = binaryninja.TransformType.DecodeTransform

    def perform_decode(self, data, params):
        """
        void* rax_2 = HeapAlloc(hHeap: GetProcessHeap(), dwFlags: HEAP_ZERO_MEMORY, dwBytes: sx.q(arg2))
        for (int32_t i = 0; i u< arg2; i = i + 1)
            char var_24_1 = 0x13
            if (modu.dp.d(0:i, 2) == 0)>
                var_24_1 = 0x37
            *(rax_2 + zx.q(i)) = *(arg1 + zx.q(i)) ^ var_24_1
        return rax_2
        """
        log_info("Performing decode")
        result = bytearray()
        for i in range(len(data)):
            if i % 2 == 0:
                result.append(data[i] ^ 0x13)
            else:
                result.append(data[i] ^ 0x37)
        return result

    def perform_encode(self, data, params):
        return self.perform_decode(data, params)


# Register plugin
DecodeString.register()

```

Preferences:

![image](https://github.com/Vector35/binaryninja-api/assets/13900053/4c7c1536-135c-4a43-9475-a675f21faedc)

Pip list:

```sh
pip list

Package        Version
-------------- -----------
colorama       0.4.4
pip            23.2.1
pydantic       1.7.3
pydev          0.0.1
pydevd         2.10.0
pydevd-pycharm 211.7142.13
setuptools     68.2.0
wheel          0.41.2
```</div>

**Comment by xusheng6** [comment]
This is similar to https://github.com/Vector35/binaryninja-api/issues/4663

**Comment by fuzyll** [comment]
From the discussion, the following appears to have solved the issue for the user:

```
pip install --force-reinstall pydevd-pycharm~=233.13135.95
```

Closing this as resolved since it appears it's not our issue.
