### ISSUE TITLE
nes arch plugin broken on dev channel

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#498]
nes plugin: https://github.com/Vector35/binaryninja-api/blob/master/python/examples/nes.py

when I try to load pwn adventure Z:

Traceback (most recent call last):
  File "/home/username/binaryninja/plugins/../python/binaryninja/**init**.py", line 1502, in _get_entry_point
    return self.perform_get_entry_point()
  File "/home/username/.binaryninja/plugins/nes.py", line 665, in perform_get_entry_point
    return struct.unpack("<H", str(self.perform_read(0xfffc, 2)))[0]
  File "/home/username/.binaryninja/plugins/nes.py", line 604, in perform_read
    if addr >= (0x8000 + self.rom_length):
AttributeError: 'NESViewBank' object has no attribute 'rom_length'

Traceback (most recent call last):
  File "/home/username/binaryninja/plugins/../python/binaryninja/**init**.py", line 1045, in _create
    view = cls(BinaryView(file_metadata, handle = core.BNNewViewReference(data)))
  File "/home/username/.binaryninja/plugins/nes.py", line 675, in __init__
    NESView.**init**(self, data)
  File "/home/username/.binaryninja/plugins/nes.py", line 503, in **init**
    self.data = data
  File "/home/username/binaryninja/plugins/../python/binaryninja/**init**.py", line 3392, in **setattr**
    raise AttributeError, "attribute '%s' is read only" % name
AttributeError: attribute 'data' is read only

Traceback (most recent call last):
  File "/home/username/binaryninja/plugins/../python/binaryninja/**init**.py", line 1502, in _get_entry_point
    return self.perform_get_entry_point()
  File "/home/username/.binaryninja/plugins/nes.py", line 665, in perform_get_entry_point
    return struct.unpack("<H", str(self.perform_read(0xfffc, 2)))[0]
  File "/home/username/.binaryninja/plugins/nes.py", line 604, in perform_read
    if addr >= (0x8000 + self.rom_length):
AttributeError: 'NESViewBank' object has no attribute 'rom_length'

etc...

**Comment by lucasduffey** [comment]
I think the core issue the is "AttributeError: attribute 'data' is read only"

link to exact line: https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/nes.py#L524

**Comment by plafosse** [comment]
Fixed in dev
