### ISSUE TITLE
MediumLevelILFunction.replace_expr() gets access violation

### ISSUE THREAD

**Issue by samrussell** [Vector35/binaryninja-api#5150]
**Version and Platform (required):**
- Binary Ninja Version: 4911
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**

I'm building a MLIL workflow and have this code

```
def optimize16bitloads(analysis_context):
	# iterate over mlil basic blocks
	updated = False
	# what if we ignore basic blocks
	#for block in analysis_context.mlil.basic_blocks:
	# iterate over instructions and test our condition
	candidates = []
	for instruction in analysis_context.mlil:
		if isinstance(instruction, MediumLevelILSetVarField):
			# candidate, check it was defined in another MediumLevelILSetVarField
			prev = analysis_context.mlil.get_ssa_var_definition(instruction.ssa_form.prev)
			if isinstance(prev, MediumLevelILSetVarField):
				#print("found 2x setvarfield at %s" % hex(instruction.instr.address))
				# make sure offsets are different and we are good
				if prev.offset != instruction.offset and instruction.instr.address == 34:
					candidates.append(instruction)
	# now we've finished with the iterator we can destroy things
	if candidates:
		print(candidates)
		print(candidates[0])
		print(candidates[0].src)
		print(candidates[0].dest)
	for instruction in candidates:
		prev = analysis_context.mlil.get_ssa_var_definition(instruction.ssa_form.prev)
		# get them in order
		instrs_by_offset = {x.offset:x for x in [instruction, prev]}
		# simple case
		if isinstance(instrs_by_offset[1].src, MediumLevelILConst) and instrs_by_offset[1].src.value.value == 0:
			dest = instruction.dest
			src = instrs_by_offset[0].src
			new_instruction = mlil.expr(MediumLevelILOperation.MLIL_SET_VAR, dest.index, src.expr_index)
			nop_instruction = mlil.expr(MediumLevelILOperation.MLIL_NOP)
			analysis_context.mlil.replace_expr(instruction, new_instruction)
			analysis_context.mlil.replace_expr(prev, nop_instruction)
			#analysis_context.mlil.append(new_instruction)
			#analysis_context.mlil.append(nop_instruction)
			updated = True
    # we need to redo the ssa then
	if updated:
		analysis_context.mlil.generate_ssa_form()

wf = Workflow().clone("Optimize16BitLoadsWorkflow")
wf.register_activity(Activity("extension.smsworkflow.optimize16bitloads", action=optimize16bitloads))
wf.insert("core.function.analyzeTailCalls", ["extension.smsworkflow.optimize16bitloads"])
wf.register()
```

This is similar to a LLIL workflow I've used in the past. The workflow always crashes at the mlil.replace_expr() with the following output

```
[Default] Traceback (most recent call last):
[Default]   File "C:\Users\Sam\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\workflow.py", line 150, in _action
[Default]     self.action(AnalysisContext(ac))
[Default]   File "<console>", line 33, in optimize16bitloads
[Default]   File "C:\Users\Sam\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\mediumlevelil.py", line 3348, in replace_expr
[Default]     core.BNReplaceMediumLevelILExpr(self.handle, original, new)
[Default]   File "C:\Users\Sam\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\_binaryninjacore.py", line 47483, in BNReplaceMediumLevelILExpr
[Default]     return _BNReplaceMediumLevelILExpr(func, expr, newExpr)
[Default] OSError: exception: access violation reading 0x00000244FF1E7C20
```

**Comment by bpotchik** [comment]
Looks like prev is an ssa expr index, but you're replacing in non-ssa form.

**Comment by samrussell** [comment]
`get_ssa_var_definition()` appears to return a non-ssa form, and both appear to have the same expression index (at least in the cases I tested)

**Comment by samrussell** [comment]
Ok this was completely my bug, it's the `mlil.expr()` that should have been `analysis_context.mlil`, so sorry for wasting your time, have a good day
