### ISSUE TITLE
Type.int bug

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#557]
**Error**
```
>>> Type.int(Architecture.default_int_size)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/noot/binaryninja/plugins/../python/binaryninja/__init__.py", line 4323, in int
    return Type(core.BNCreateIntegerType(width, sign))
  File "/home/noot/binaryninja/plugins/../python/binaryninja/_binaryninjacore.py", line 2908, in BNCreateIntegerType
    result = _BNCreateIntegerType(*args)
TypeError: this function takes at least 3 arguments (2 given)
```

```Type.int``` definition in [```__init__.py```](https://github.com/Vector35/binaryninja-api/blob/dev/python/__init__.py#L4335)
```
@classmethod
def int(self, width, sign = True):
    return Type(core.BNCreateIntegerType(width, sign))
```

C++ API in [```binaryninjacore.h```](https://github.com/Vector35/binaryninja-api/blob/dev/binaryninjacore.h#L1931)
```
BINARYNINJACOREAPI BNType* BNCreateIntegerType(size_t width, bool sign, const char* altName);
```

**Comment by psifertex** [comment]
Fixed in dev, thanks.
