### ISSUE TITLE
 global name 'BNFreeTypeParserResult' is not defined

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#576]
# repro
```
from os.path import expanduser
file_path = "%s/binaryninja/types/linux.c" % expanduser("~")

Architecture.parse_types_from_source_file(bv.arch, file_path)
```

# error
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/binaryninja/plugins/../python/binaryninja/__init__.py", line 7494, in parse_types_from_source_file
    BNFreeTypeParserResult(parse)
NameError: global name 'BNFreeTypeParserResult' is not defined
```

**Comment by psifertex** [comment]
Thanks for the report -- should be fixed in dev after it finishes building.
