### ISSUE TITLE
BinaryViewType.get_view_of_file doesn't work on bndb files

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#602]
Ubuntu 16 LTS. Professional. Dev channel.
```
>>> file_path = "%s/Documents/android_images/wpa_supplicant.symbols.bndb" % os.path.expanduser("~")
>>> os.path.isfile(file_path)
True

>>> a = BinaryViewType.get_view_of_file(file_path)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/binaryninja/plugins/../python/binaryninja/binaryview.py", line 331, in get_view_of_file
    bv.update_analysis_and_wait()
AttributeError: 'NoneType' object has no attribute 'update_analysis_and_wait'
```

**Comment by lucasduffey** [comment]
the workaround for now is to use `BinaryViewType['ELF'].open`

**Comment by joshwatson** [comment]
```python
from binaryninja import *
bv = FileMetadata().open_existing_database('/path/to/executable')
print bv.view # 'Hex:Raw'
elf = bv.get_view_of_type('ELF')
```

**Comment by lucasduffey** [comment]
@joshwatson - try this after your code though.
```
bv.functions 
```

**Comment by plafosse** [comment]
I believe this was fixed a while ago:

```
>>> bv = BinaryViewType.get_view_of_file('/Users/peterl/Downloads/foo.bndb')
>>> bv.functions[0]
<func: x86@0x5a2ff670>
>>> 
```
