### ISSUE TITLE
IndexError("index out of range") when is_valid handler set by plugin command

### ISSUE THREAD

**Issue by droe** [Vector35/binaryninja-api#6254]
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6455 Personal (02c8da1e)
- OS: macOS
- OS Version: 14.x
- CPU Architecture: arm64

**Bug Description:**
Binary Ninja spews exceptions when python plugins are loaded that register a plugin command with an is_valid handler.  The exceptions seem unrelated to plugin code.

I'm getting bug reports for [my plugin](https://github.com/droe/binja-blocks) for this, but I think the issue is in Binary Ninja API or core.

**Steps To Reproduce:**
1. Open a target in Binary Ninja
2. Double-click on a function call in linear HLIL view to jump to that function
3. Return to the previous location by pressing Escape
4. See exceptions in the console log

Precondition seems to be the presence of a plugin with an is_valid handler.  Notably, it is not required to actually execute any plugin commands.  Just the presence of an is_valid handler seems enough to cause this.

**Expected Behavior:**
No exceptions raised.

**Screenshots/Video Recording:**

A lot of these in console:
```
[Default] Traceback (most recent call last):
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 361, in _high_level_il_instruction_is_valid
[Default]     return is_valid(view_obj, func_obj[instr])
[Default]   File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/highlevelil.py", line 2477, in __getitem__
[Default]     raise IndexError("index out of range")
[Default] IndexError: index out of range
```

**Binary:**
Seems to repro with any binary.

**Additional Information:**
n/a

**Comment by negasora** [comment]
I'm not able to reproduce this with Binary Ninja Personal `4.2.6455` and binja-blocks 0.3.6. Can you share a file this happens with?

**Comment by droe** [comment]
It repros easily for me with `/usr/libexec/biometrickitd` on macOS 14, arm64e slice.  Also repros with any other MachOs I tried, including for iOS.  I don't work other architectures much so not sure if it's specific to any of arm64, MachO, or ObjC workflow.  fwiw, I have reports from two users that they also frequently encounter this.

**Comment by fuzyll** [comment]
I was able to get this to reproduce with `/usr/libexec/biometrickitd` on 4.2.6455 Personal and Ultimate, in addition to 4.3.6564-dev Ultimate, but _only_ on a macOS client.

**Comment by droe** [comment]
I've disabled `is_valid` in the Apple Blocks plugin to work around this issue.  Anyone attempting to reproduce the bug using Apple Blocks will want to make sure to use 0.3.8 or earlier, not latest `main` nor any future release > 0.3.8.

**Comment by xusheng6** [comment]
This is caused by the fact that the `instrIndex` of the `UIActionContext` can hold an incorrect value after we double-click a function to navigate to it and then press Escape to go back: 

```
>>> hex(current_ui_action_context.instrIndex)
'0x10910c1a0'
```

This has nothing to do with the binary, and probably also nothing to do with the OS

**Comment by xusheng6** [comment]
The error message itself has been fixed in https://github.com/Vector35/binaryninja/commit/53220ec5371de30d64a0bb738a0e8bbe3e781af0. However, the fix is temporary -- despite that error message is gone, the callback is given an invalid (-1) instrIndex after navigating to a history entry in the linear view. I will create a new issue to track it seperately
