### ISSUE TITLE
Dev build reliable analysis segfault

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#658]
Build `ad1108a6` on linux x64 while loading http://cyberjes.us/cayley
```
Thread 13 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe513a700 (LWP 11806)]
0x00007ffff62c3489 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
(gdb) i r
rax            0x7fff949c60a0   140735686664352
rbx            0x7fff94a007c0   140735686903744
rcx            0x7ffff62c3545   140737323480389
rdx            0x1      1
rsi            0x1      1
rdi            0x7fff94a007c0   140735686903744
rbp            0x7fffe5139610   0x7fffe5139610
rsp            0x7fffe493afd0   0x7fffe493afd0
r8             0x170    368
r9             0x60     96
r10            0x30     48
r11            0x7fff949cabe0   140735686683616
r12            0x1      1
r13            0x1      1
r14            0x7fffe5139610   140737036654096
r15            0x7fff949b3970   140735686588784
rip            0x7ffff62c3489   0x7ffff62c3489
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

The end of the backtrace is:
```
#52375 0x00007ffff62c3554 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52376 0x00007ffff62c97df in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52377 0x00007ffff629c207 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52378 0x00007ffff62b9ae4 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52379 0x00007ffff60dacc3 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52380 0x00007ffff60f9060 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52381 0x00007ffff612c617 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52382 0x00007ffff60c0d9a in  () at /opt/binaryninja/libbinaryninjacore.so.1
#52383 0x00007ffff3bec970 in std::execute_native_thread_routine_compat(void*) (__p=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/src/c++11/thread.cc:110
#52384 0x00007ffff3ec02e7 in start_thread () at /usr/lib/libpthread.so.0
#52385 0x00007ffff334f54f in clone () at /usr/lib/libc.so.6
```
With the top address (0x00007ffff62c3554) repeated 52k times.

**Comment by D0ntPanic** [comment]
Fixed in dev build 711
