### ISSUE TITLE
Another dev build analysis segfault

### ISSUE THREAD

**Issue by nshp** [Vector35/binaryninja-api#660]
Once again, build `ad1108a6` on linux x64 while loading http://cyberjes.us/datalog
```
Thread 13 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcc020700 (LWP 12056)]
0x00007ffff62b6c20 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
(gdb) bt
#0  0x00007ffff62b6c20 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff62b8db8 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff60dacc3 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff60f9060 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff612c617 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff60c0d9a in  () at /opt/binaryninja/libbinaryninjacore.so.1
#6  0x00007ffff3bec970 in std::execute_native_thread_routine_compat(void*) (__p=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/src/c++11/thread.cc:110
#7  0x00007ffff3ec02e7 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff334f54f in clone () at /usr/lib/libc.so.6
(gdb) i r
rax            0x11c8   4552
rbx            0x7fffc50721c8   140736498966984
rcx            0x7fffc50a7a10   140736499186192
rdx            0x7fffc4000078   140736481722488
rsi            0x0      0
rdi            0x7fffc4000020   140736481722400
rbp            0x7fffc5043260   0x7fffc5043260
rsp            0x7fffcc01f530   0x7fffcc01f530
r8             0x3      3
r9             0x1800000003800000       1729382256968990720
r10            0x7fffca5b9210   140736588386832
r11            0x7fffc5074de0   140736498978272
r12            0x7fffcc01f5d0   140736616068560
r13            0x7fffc50721c8   140736498966984
r14            0x5      5
r15            0x7fffca603990   140736588691856
rip            0x7ffff62b6c20   0x7ffff62b6c20
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

**Comment by nshp** [comment]
Similar crash from http://cyberjes.us/libperl.so
```
Thread 14 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcc053700 (LWP 12119)]
0x00007ffff62b6c20 in ?? () from /opt/binaryninja/libbinaryninjacore.so.1
(gdb) bt
#0  0x00007ffff62b6c20 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff62b97f4 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff60dacc3 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff60f9060 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff612c617 in  () at /opt/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff60c0d9a in  () at /opt/binaryninja/libbinaryninjacore.so.1
#6  0x00007ffff3bec970 in std::execute_native_thread_routine_compat(void*) (__p=<optimized out>) at /build/gcc-multilib/src/gcc/libstdc++-v3/src/c++11/thread.cc:110
#7  0x00007ffff3ec02e7 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff334f54f in clone () at /usr/lib/libc.so.6
(gdb) i r
rax            0x5278   21112
rbx            0x7fffafe43948   140736144357704
rcx            0x0      0
rdx            0xffffffff       4294967295
rsi            0x0      0
rdi            0x7fffbc000040   140736347504704
rbp            0x7fff933960b0   0x7fff933960b0
rsp            0x7fffcc052530   0x7fffcc052530
r8             0x7fff8a359d10   140735512157456
r9             0x1800000003900000       1729382256970039296
r10            0x7fff8b989060   140735535419488
r11            0x7fff93ee41d0   140735675253200
r12            0x7fffcc0525d0   140736616277456
r13            0x7fffafe43948   140736144357704
r14            0x0      0
r15            0x7fff60000cf0   140734804004080
rip            0x7ffff62b6c20   0x7ffff62b6c20
eflags         0x10202  [ IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

**Comment by D0ntPanic** [comment]
Fixed in dev build 711
