### ISSUE TITLE
Crash in Token Parsing

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#735]
I'm developing a architecture plugin and I accidentally returned a list of tuples from `perform_get_instruction_text` . I got this segmentation fault:

```
ELF parsing took 0.029 seconds
Starting analysis update
Disassembling 966 functions
0x4181a0: Basic block at 0x4181a0 - 0x4181ee
[('MOV #', '0x0'), (', ', 'r14')]
0x414760: Basic block at 0x414760 - 0x4147aa
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/architecture.py", line 472, in _get_instruction_text
    if isinstance(tokens[i].type, str):
AttributeError: 'tuple' object has no attribute 'type'
Process 11850 stopped
* thread #15, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001006cd98b libbinaryninjacore.dylib`___lldb_unnamed_symbol1108$$libbinaryninjacore.dylib + 139
libbinaryninjacore.dylib`___lldb_unnamed_symbol1108$$libbinaryninjacore.dylib:
->  0x1006cd98b <+139>: mov    ecx, dword ptr [rax + r14]
    0x1006cd98f <+143>: mov    dword ptr [rbp - 0xa4], ecx
    0x1006cd995 <+149>: mov    r15d, dword ptr [rax + r14 + 0x28]
    0x1006cd99a <+154>: mov    r13, qword ptr [rax + r14 + 0x8]
(lldb)
```

**Comment by plafosse** [comment]
Need a bit more info what was in the list of tuples? Or more detailed steps on how to repro.

**Comment by withzombies** [comment]
Use [this architecture plugin](https://gist.github.com/withzombies/13ff010c063e455fa8f5bcdab756f099) on [this file](https://github.com/JonathanSalwan/binary-samples/blob/master/elf-Linux-SuperH4-bash).

**Comment by bpotchik** [comment]
I believe this was fixed a while ago as this example no longer segfaults.
