### ISSUE TITLE
save crash

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#768]
triggered on Ubuntu 16 LTS

1) opened dll
2) loaded pdb via tools => load pdb
3) bndb file was saved
4) bndb file was opened
5) If I try to save again, crash is triggered

```
Thread 1 "binaryninja" received signal SIGSEGV, Segmentation fault.
0x00007ffff65328dc in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
(gdb) bt
#0  0x00007ffff65328dc in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff6532a74 in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff6247adc in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff625a5ed in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff625aa4f in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff625d087 in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#6  0x00007ffff625ae5c in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#7  0x00007ffff625c3a9 in BNSaveAutoSnapshotWithProgress () from /home/user/binaryninja/libbinaryninjacore.so.1
#8  0x000000000051c2a2 in BinaryNinja::FileMetadata::SaveAutoSnapshot(BinaryNinja::BinaryView*, std::function<void (unsigned long, unsigned long)> const&) ()
#9  0x000000000044ea48 in MainWindow::saveFileForView(ViewFrame*) ()
#10 0x0000000000514435 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#11 0x00007ffff451ecef in QMetaObject::activate(QObject*, int, int, void**) () from /home/user/binaryninja/libQt5Core.so.5
#12 0x00007ffff563e952 in QAction::triggered(bool) () from /home/user/binaryninja/libQt5Widgets.so.5
#13 0x00007ffff56414ad in QAction::activate(QAction::ActionEvent) () from /home/user/binaryninja/libQt5Widgets.so.5
#14 0x00007ffff5641e27 in QAction::event(QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#15 0x00007ffff564804c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#16 0x00007ffff564c488 in QApplication::notify(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#17 0x00007ffff44f5e80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Core.so.5
#18 0x00007ffff4e2078a in QShortcutMap::dispatchEvent(QKeyEvent*) () from /home/user/binaryninja/libQt5Gui.so.5
#19 0x00007ffff4e20874 in QShortcutMap::tryShortcut(QKeyEvent*) () from /home/user/binaryninja/libQt5Gui.so.5
#20 0x00007ffff4ddca66 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) ()
   from /home/user/binaryninja/libQt5Gui.so.5
#21 0x00007ffff4df1774 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /home/user/binaryninja/libQt5Gui.so.5
#22 0x00007ffff4df6465 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/user/binaryninja/libQt5Gui.so.5
#23 0x00007ffff4dd76a3 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/binaryninja/libQt5Gui.so.5
#24 0x00007fffe6fa4720 in ?? () from /home/user/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#25 0x00007ffff2606197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff26063f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff260649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff45454e7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/binaryninja/libQt5Core.so.5
#29 0x00007ffff44f3efa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/binaryninja/libQt5Core.so.5
#30 0x00007ffff44fbd9d in QCoreApplication::exec() () from /home/user/binaryninja/libQt5Core.so.5
#31 0x0000000000438094 in main ()

(gdb) x/100i 0x00007ffff65328dc - 80
   0x7ffff653288c:	add    BYTE PTR [rax],al
   0x7ffff653288e:	add    BYTE PTR [rax],al
   0x7ffff6532890:	mov    rax,QWORD PTR [rdi+0x60]
   0x7ffff6532894:	sub    rax,QWORD PTR [rdi+0x58]
   0x7ffff6532898:	sar    rax,0x3
   0x7ffff653289c:	ret    
   0x7ffff653289d:	nop    DWORD PTR [rax]
   0x7ffff65328a0:	mov    rax,QWORD PTR [rdi+0x98]
   0x7ffff65328a7:	ret    
   0x7ffff65328a8:	nop    DWORD PTR [rax+rax*1+0x0]
   0x7ffff65328b0:	mov    rax,QWORD PTR [rdi+0x20]
   0x7ffff65328b4:	mov    rax,QWORD PTR [rax-0x18]
   0x7ffff65328b8:	ret    
   0x7ffff65328b9:	nop
   0x7ffff65328ba:	nop    WORD PTR [rax+rax*1+0x0]
   0x7ffff65328c0:	push   r14
   0x7ffff65328c2:	mov    r14,rsi
   0x7ffff65328c5:	xor    esi,esi
   0x7ffff65328c7:	push   r13
   0x7ffff65328c9:	mov    r13,rdi
   0x7ffff65328cc:	push   r12
   0x7ffff65328ce:	push   rbp
   0x7ffff65328cf:	push   rbx
   0x7ffff65328d0:	sub    rsp,0x270
   0x7ffff65328d7:	call   0x7ffff65022d0
=> 0x7ffff65328dc:	cmp    DWORD PTR [r14+0xa0],0x8
   0x7ffff65328e4:	ja     0x7ffff6532da0
   0x7ffff65328ea:	mov    edx,DWORD PTR [r14+0xa0]
   0x7ffff65328f1:	lea    rax,[rip+0x9a6118]        # 0x7ffff6ed8a10
   0x7ffff65328f8:	movsxd rdx,DWORD PTR [rax+rdx*4]
   0x7ffff65328fc:	add    rax,rdx
   0x7ffff65328ff:	jmp    rax
   0x7ffff6532901:	nop    DWORD PTR [rax+0x0]
   0x7ffff6532908:	lea    rbp,[rsp+0x10]
   0x7ffff653290d:	lea    rdx,[rsp+0x9]
   0x7ffff6532912:	lea    rsi,[rip+0x9a61f0]        # 0x7ffff6ed8b09
   0x7ffff6532919:	mov    rdi,rbp
   0x7ffff653291c:	call   0x7ffff622a490 <_ZNSsC1EPKcRKSaIcE@plt>
   0x7ffff6532921:	nop    DWORD PTR [rax+0x0]
   0x7ffff6532928:	lea    rbx,[rsp+0x30]
   0x7ffff653292d:	mov    rsi,rbp
   0x7ffff6532930:	mov    rdi,rbx
   0x7ffff6532933:	call   0x7ffff65026d0
   0x7ffff6532938:	lea    rsi,[rip+0x999aa1]        # 0x7ffff6ecc3e0
   0x7ffff653293f:	mov    rdi,r13
   0x7ffff6532942:	call   0x7ffff650c9d0
   0x7ffff6532947:	mov    rsi,rbx
   0x7ffff653294a:	mov    rdi,rax
   0x7ffff653294d:	call   0x7ffff6502850
   0x7ffff6532952:	mov    rdi,rbx
   0x7ffff6532955:	call   0x7ffff6506140
   0x7ffff653295a:	mov    rax,QWORD PTR [rsp+0x10]
   0x7ffff653295f:	lea    rdi,[rax-0x18]
   0x7ffff6532963:	cmp    rdi,QWORD PTR [rip+0x185dde6]        # 0x7ffff7d90750
   0x7ffff653296a:	jne    0x7ffff6532dbe
   0x7ffff6532970:	cmp    DWORD PTR [r14+0xa0],0x8
   0x7ffff6532978:	ja     0x7ffff6532a20
   0x7ffff653297e:	mov    edx,DWORD PTR [r14+0xa0]
   0x7ffff6532985:	lea    rax,[rip+0x9a60a8]        # 0x7ffff6ed8a34
   0x7ffff653298c:	movsxd rdx,DWORD PTR [rax+rdx*4]
   0x7ffff6532990:	add    rax,rdx
   0x7ffff6532993:	jmp    rax
   0x7ffff6532995:	nop    DWORD PTR [rax]
   0x7ffff6532998:	lea    rbx,[rsp+0x1b0]
   0x7ffff65329a0:	mov    esi,0x6
   0x7ffff65329a5:	mov    rdi,rbx
   0x7ffff65329a8:	call   0x7ffff65022d0
   0x7ffff65329ad:	lea    rsi,[rip+0x9abf1e]        # 0x7ffff6ede8d2
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) i r
rax            0x7ffff6502340	140737325835072
rbx            0x7fffc97b0fa0	140736573673376
rcx            0x0	0
rdx            0xffffffffff62b740	-10307776
rsi            0x0	0
rdi            0x7fffffffc3d0	140737488339920
rbp            0x7fffffffc3a0	0x7fffffffc3a0
rsp            0x7fffffffbf20	0x7fffffffbf20
r8             0x7fffc34117a0	140736469211040
r9             0x0	0
r10            0x7fffe8006000	140737085726720
r11            0x1	1
r12            0x7fffffffc3d0	140737488339920
r13            0x7fffffffc3d0	140737488339920
r14            0x0	0
r15            0x7fffffffc540	140737488340288
rip            0x7ffff65328dc	0x7ffff65328dc
eflags         0x10203	[ CF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

**Comment by lucasduffey** [comment]
It's possible this has nothing to do with pdb.  I opened the same dll without trying to load the pdb file and got the same problem. 

The problem seems to manifest after you save the database and close binja. The next time you open the database and try to save it again it crashes on the save

**Comment by peterhuene** [comment]
I'm seeing a similar crash on Windows although with plenty of free disk space.  First save of the analysis DB succeeded.  Reopened and saved again results in an access violation:

Exception info:
```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: C0000005 (EXCEPTION_ACCESS_VIOLATION)
          ExceptionFlags: 00000000
        ExceptionAddress: 00007FF874AD73CC binaryninjacore.00007FF874AD73CC
        NumberParameters: 2
ExceptionInformation[00]: 0000000000000000 Read
ExceptionInformation[01]: 0000000000000098 Inaccessible Address
First chance exception on 00007FF874AD73CC (C0000005, EXCEPTION_ACCESS_VIOLATION)!
```

Backtrace:
```
Address           To                From              Size              Comment                                            Party                                                                                                                                                    
00000098BBF09038  00007FF874AD7695  00007FF874AD73CC  D0                binaryninjacore.00007FF874AD73CC                   User
00000098BBF09108  00007FF8747CA19A  00007FF874AD7695  4B0               binaryninjacore.00007FF874AD7695                   User
00000098BBF095B8  00007FF8747DC499  00007FF8747CA19A  150               binaryninjacore.00007FF8747CA19A                   User
00000098BBF09708  00007FF8747DD5EE  00007FF8747DC499  1B0               binaryninjacore.00007FF8747DC499                   User
00000098BBF098B8  00007FF8747DE426  00007FF8747DD5EE  B0                binaryninjacore.00007FF8747DD5EE                   User
00000098BBF09968  00007FF8747E0033  00007FF8747DE426  90                binaryninjacore.00007FF8747DE426                   User
00000098BBF099F8  00007FF6985C78FD  00007FF8747E0033  D0                binaryninjacore.00007FF8747E0033                   User
00000098BBF09AC8  00007FF69851A85B  00007FF6985C78FD  140               binaryninja.00007FF6985C78FD                       User
00000098BBF09C08  000000005F1EC4C2  00007FF69851A85B  120               binaryninja.00007FF69851A85B                       User
00000098BBF09D28  000000005F6976A2  000000005F1EC4C2  50                qt5core.000000005F1EC4C2                           User
00000098BBF09D78  000000005F7F5138  000000005F6976A2  B0                qt5widgets.000000005F6976A2                        User
00000098BBF09E28  000000005F7F4F96  000000005F7F5138  A0                qt5widgets.000000005F7F5138                        User
00000098BBF09EC8  000000005F7F9D29  000000005F7F4F96  30                qt5widgets.000000005F7F4F96                        User
00000098BBF09EF8  000000005F6D0D2C  000000005F7F9D29  1D0               qt5widgets.000000005F7F9D29                        User
00000098BBF0A0C8  000000005F7F6494  000000005F6D0D2C  90                qt5widgets.000000005F6D0D2C                        User
00000098BBF0A158  000000005F6A7F82  000000005F7F6494  30                qt5widgets.000000005F7F6494                        User
00000098BBF0A188  000000005F6A5EDE  000000005F6A7F82  660               qt5widgets.000000005F6A7F82                        User
00000098BBF0A7E8  000000005F1CB9D9  000000005F6A5EDE  80                qt5widgets.000000005F6A5EDE                        User
00000098BBF0A868  000000005F6A92A3  000000005F1CB9D9  110               qt5core.000000005F1CB9D9                           User
00000098BBF0A978  000000005F6F8C13  000000005F6A92A3  1A0               qt5widgets.000000005F6A92A3                        User
00000098BBF0AB18  000000005F6F75A5  000000005F6F8C13  60                qt5widgets.000000005F6F8C13                        User
00000098BBF0AB78  000000005F6A7F82  000000005F6F75A5  30                qt5widgets.000000005F6F75A5                        User
00000098BBF0ABA8  000000005F6A6935  000000005F6A7F82  660               qt5widgets.000000005F6A7F82                        User
00000098BBF0B208  000000005F1CB9D9  000000005F6A6935  80                qt5widgets.000000005F6A6935                        User
00000098BBF0B288  00007FF87C391E54  000000005F1CB9D9  490               qt5core.000000005F1CB9D9                           User
00000098BBF0B718  00007FF87C377EBC  00007FF87C391E54  40                qt5gui.00007FF87C391E54                            User
00000098BBF0B758  000000005F214065  00007FF87C377EBC  110               qt5gui.00007FF87C377EBC                            User
00000098BBF0B868  00007FF8A758BC50  000000005F214065  160               qt5core.000000005F214065                           System
00000098BBF0B9C8  00007FF8A758B5CF  00007FF8A758BC50  80                user32.00007FF8A758BC50                            System
00000098BBF0BA48  000000005F2137A6  00007FF8A758B5CF  33A0              user32.00007FF8A758B5CF                            User
00000098BBF0EDE8  00007FF8810522F9  000000005F2137A6  30                qt5core.000000005F2137A6                           User
00000098BBF0EE18  000000005F1C7FD3  00007FF8810522F9  80                qwindows.00007FF8810522F9                          User
00000098BBF0EE98  000000005F1CA617  000000005F1C7FD3  70                qt5core.000000005F1C7FD3                           User
00000098BBF0EF08  00007FF69850DE8B  000000005F1CA617  7A0               qt5core.000000005F1CA617                           User
00000098BBF0F6A8  00007FF6985E3564  00007FF69850DE8B  90                binaryninja.00007FF69850DE8B                       User
00000098BBF0F738  00007FF6985E2A43  00007FF6985E3564  40                binaryninja.00007FF6985E3564                       User
00000098BBF0F778  00007FF8A9EE2774  00007FF6985E2A43  30                binaryninja.00007FF6985E2A43                       System
00000098BBF0F7A8  00007FF8AA020D51  00007FF8A9EE2774  50                kernel32.00007FF8A9EE2774                          System
00000098BBF0F7F8  0000000000000000  00007FF8AA020D51                    ntdll.00007FF8AA020D51                             User
```

Faulting instruction:
```
    00007FF874AD73B8 | E8 63 D0 FD FF           | call <binaryninjacore.sub_7FF874AB4420> |
    00007FF874AD73BD | C7 45 E7 01 00 00 00     | mov dword ptr ss:[rbp-19],1             |
    00007FF874AD73C4 | 48 8D 45 BF              | lea rax,qword ptr ss:[rbp-41]           |
    00007FF874AD73C8 | 48 89 45 B7              | mov qword ptr ss:[rbp-49],rax           |
==> 00007FF874AD73CC | 8B 97 98 00 00 00        | mov edx,dword ptr ds:[rdi+98]           |
    00007FF874AD73D2 | 48 8D 4D 0F              | lea rcx,qword ptr ss:[rbp+F]            |
    00007FF874AD73D6 | E8 45 FD FF FF           | call <binaryninjacore.sub_7FF874AD7120> |
    00007FF874AD73DB | 90                       | nop                                     |
```

Registers:
```
RAX : 00000098BBF08F98
RCX : 00000098BBF09068
RDX : 00000000FFFFFFFF
RBX : 000002786B9D6990
RDI : 0000000000000000
RBP : 00000098BBF08FD9
RSI : 00000098BBF09068
RSP : 00000098BBF08F70
R8  : 0000000000000000
R9  : 000002786B966801
R10 : 0000000000000000
R11 : 00000098BBF09010
R12 : 000002786B92A0F8
R13 : 00000098BBF097C0
R14 : 00000098BBF09D50
R15 : 000002786B78DC70
RIP : 00007FF874AD73CC     binaryninjacore.00007FF874AD73CC
RFLAGS : 0000000000010206
```
