### ISSUE TITLE
null pointer deref in libbinaryninjacore so

### ISSUE THREAD

**Issue by bemitc** [Vector35/binaryninja-api#777]
Binja crash upon loading the ShadowPad malware sample @ https://www.hybrid-analysis.com/sample/fba0c928e2657b6cd074824f98f6f11437815ad88097d5d22100e9d9f334bbaf?environmentId=100

Version: 1.0.873-Dev on Linux (ubuntu 16.04)

```
Thread 1 "binaryninja" received signal SIGSEGV, Segmentation fault.
0x00007ffff63d539e in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
(gdb) bt
#0  0x00007ffff63d539e in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff63d8afb in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#2  0x00007ffff63d86eb in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff63d777a in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff63d8513 in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff6262e02 in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#6  0x00007ffff6264e0a in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#7  0x00007ffff6266c98 in ?? () from /home/brian/binaryninja/libbinaryninjacore.so.1
#8  0x00007ffff6268fd0 in BNCreateBinaryViewOfType () from /home/brian/binaryninja/libbinaryninjacore.so.1
(gdb) x/1i 0x00007ffff63d539e
=> 0x7ffff63d539e:	cmpb   $0x0,0x33(%rsi)
(gdb) info reg rsi
rsi            0x0	0
```

[462a02a8094e833fd456baf0a6d4e18bb7dab1a9f74d5f163a8334921a4ffde8.zip](https://github.com/Vector35/binaryninja-api/files/1239546/462a02a8094e833fd456baf0a6d4e18bb7dab1a9f74d5f163a8334921a4ffde8.zip)

**Comment by plafosse** [comment]
Fixed as of build 889.
