### ISSUE TITLE
Segmentation fault in BinaryNinja::Architecture::AssembleCallback

### ISSUE THREAD

**Issue by zaddach** [Vector35/binaryninja-api#779]
I am trying to run the example plugin for extending the x86 architecture, in [examples/x86_extension](../tree/dev/examples/x86_extension). When I copy the plugin to `~/.binaryninja/plugins/`, run binaryninja on an x86 (PE) binary and right-click the code, the application segfaults. The stack trace is below. (The generation of the LLIL code for the instruction in the plugin works, though)

```
Thread 1 "binaryninja" received signal SIGSEGV, Segmentation fault.
0x00007ffff62d72ca in ?? () from /home/jzaddach/binaryninja/libbinaryninjacore.so.1
(gdb) bt
#0  0x00007ffff62d72ca in ?? () from /home/jzaddach/binaryninja/libbinaryninjacore.so.1
#1  0x00007ffff62d846c in BNSetDataBufferContents () from /home/jzaddach/binaryninja/libbinaryninjacore.so.1
#2  0x00007fffcc808cc8 in BinaryNinja::Architecture::AssembleCallback (ctxt=<optimized out>, code=0x1238270 "\207\313\017ρ\341\305\023n\322=\365", <incomplete sequence \371>, addr=4201657, result=0x2, errors=0x0)
    at architecture.cpp:369
#3  0x00007ffff62e0b55 in ?? () from /home/jzaddach/binaryninja/libbinaryninjacore.so.1
#4  0x000000000046bd7c in DisassemblyView::contextMenu() ()
#5  0x00000000004722e1 in DisassemblyView::mousePressEvent(QMouseEvent*) ()
#6  0x00007ffff5739a59 in QWidget::event(QEvent*) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#7  0x00007ffff583156e in QFrame::event(QEvent*) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#8  0x00007ffff45a4bf3 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Core.so.5
#9  0x00007ffff56f7025 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#10 0x00007ffff56fbf0e in QApplication::notify(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#11 0x00007ffff45a4e80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Core.so.5
#12 0x00007ffff56faa33 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#13 0x00007ffff57545da in ?? () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#14 0x00007ffff57566db in ?? () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#15 0x00007ffff56f704c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#16 0x00007ffff56fb488 in QApplication::notify(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Widgets.so.5
#17 0x00007ffff45a4e80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/jzaddach/binaryninja/libQt5Core.so.5
#18 0x00007ffff4ea397b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /home/jzaddach/binaryninja/libQt5Gui.so.5
#19 0x00007ffff4ea5485 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/jzaddach/binaryninja/libQt5Gui.so.5
#20 0x00007ffff4e866a3 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/jzaddach/binaryninja/libQt5Gui.so.5
#21 0x00007fffe8f11720 in ?? () from /home/jzaddach/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#22 0x00007ffff26b5197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff26b53f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff26b549c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff45f44e7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/jzaddach/binaryninja/libQt5Core.so.5
#26 0x00007ffff45a2efa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/jzaddach/binaryninja/libQt5Core.so.5
#27 0x00007ffff45aad9d in QCoreApplication::exec() () from /home/jzaddach/binaryninja/libQt5Core.so.5
#28 0x0000000000434ea4 in main ()
(gdb) select 2
(gdb) print buf.GetLength()
$1 = 0
(gdb) print buf.GetData()
$2 = (void *) 0x1237860
```

That's in [architecture.cpp line 369](../blob/dev/architecture.cpp#L369).

I'm using commit 110f16b, Binja 1.0.776 (6573250f), on Ubuntu 16.04.2 kernel  4.10.0-32 x86_64. The built plugin is [attached](https://github.com/Vector35/binaryninja-api/files/1262738/libx86_extension.so.zip). Thanks for any help.

**Comment by D0ntPanic** [comment]
The implementation of architecture extensions has changed significantly and this does not happen on the latest dev. Marking as fixed in build 1064
