### ISSUE TITLE
ffi_closure_unix64_inner SEGFAULT

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#830]
# reproduction
```
# Ubuntu 16 LTS (fully patched)

cd ~/.binaryninja/plugins/
git clone https://github.com/lucasduffey/binja_smali

mkdir -p /tmp/binja && cd /tmp/binja
wget https://github.com/latenssi/csawctf13/raw/master/herpderperp/herpderper.apk

ulimit -c unlimited # enable core dumps
~/binaryninja/binaryninja --debug --stderr-log herpderper.apk
```

# core dump
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb698b20ae1 in ffi_closure_unix64_inner () from /usr/lib/x86_64-linux-gnu/libffi.so.6
[Current thread is 1 (Thread 0x7fb6a24da780 (LWP 3934))]
gdb-peda$ bt
#0  0x00007fb698b20ae1 in ffi_closure_unix64_inner () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#1  0x00007fb698b20fa8 in ffi_closure_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#2  0x00007fb6a0770701 in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#3  0x00007fb6a07707bb in BNGetBinaryViewTypesForData () from /home/user/binaryninja/libbinaryninjacore.so.1
#4  0x000000000052da05 in BinaryNinja::BinaryViewType::GetViewTypesForData(BinaryNinja::BinaryView*) ()
#5  0x000000000046c869 in FileContext::getAvailableTypes() ()
#6  0x000000000045338d in ViewFrame::getAvailableTypes() const ()
#7  0x000000000044ab0b in MainWindow::currentTabChanged(QTabWidget*, int) ()
#8  0x00000000005195a5 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#9  0x00007fb69ea05cef in QMetaObject::activate(QObject*, int, int, void**) () from /home/user/binaryninja/libQt5Core.so.5
#10 0x00007fb69fcd132e in QTabWidget::currentChanged(int) () from /home/user/binaryninja/libQt5Widgets.so.5
#11 0x00007fb69fcd3427 in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#12 0x00007fb69ea05cef in QMetaObject::activate(QObject*, int, int, void**) () from /home/user/binaryninja/libQt5Core.so.5
#13 0x00007fb69fcc524e in QTabBar::currentChanged(int) () from /home/user/binaryninja/libQt5Widgets.so.5
#14 0x00007fb69fcca2e0 in QTabBar::setCurrentIndex(int) () from /home/user/binaryninja/libQt5Widgets.so.5
#15 0x00007fb69fcce89b in QTabBar::insertTab(int, QIcon const&, QString const&) () from /home/user/binaryninja/libQt5Widgets.so.5
#16 0x00007fb69fcd1eec in QTabWidget::insertTab(int, QWidget*, QIcon const&, QString const&) () from /home/user/binaryninja/libQt5Widgets.so.5
#17 0x00007fb69fcd1f94 in QTabWidget::insertTab(int, QWidget*, QString const&) () from /home/user/binaryninja/libQt5Widgets.so.5
#18 0x000000000044730d in MainWindow::createTab(FileContext*, QString const&, bool) ()
#19 0x000000000044e6bb in MainWindow::openFilename(QString const&) ()
#20 0x000000000049487b in NewTabWidget::recentFile(QString const&) ()
#21 0x00007fb69ea05cef in QMetaObject::activate(QObject*, int, int, void**) () from /home/user/binaryninja/libQt5Core.so.5
#22 0x00007fb69fc6be52 in QLabel::linkActivated(QString const&) () from /home/user/binaryninja/libQt5Widgets.so.5
#23 0x00007fb69fc6eb49 in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#24 0x00007fb69ea05cef in QMetaObject::activate(QObject*, int, int, void**) () from /home/user/binaryninja/libQt5Core.so.5
#25 0x00007fb69fcefc95 in QWidgetTextControl::linkActivated(QString const&) () from /home/user/binaryninja/libQt5Widgets.so.5
#26 0x00007fb69fcf5084 in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#27 0x00007fb69fcf5f46 in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#28 0x00007fb69fcfaec1 in QWidgetTextControl::processEvent(QEvent*, QMatrix const&, QWidget*) () from /home/user/binaryninja/libQt5Widgets.so.5
#29 0x00007fb69fcf1deb in QWidgetTextControl::processEvent(QEvent*, QPointF const&, QWidget*) () from /home/user/binaryninja/libQt5Widgets.so.5
#30 0x00007fb69fc6da88 in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#31 0x00007fb69fb71308 in QWidget::event(QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#32 0x00007fb69fc6956e in QFrame::event(QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#33 0x00007fb69fb2f04c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#34 0x00007fb69fb33f0e in QApplication::notify(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#35 0x00007fb69e9dce80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Core.so.5
#36 0x00007fb69fb32a33 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /home/user/binaryninja/libQt5Widgets.so.5
#37 0x00007fb69fb8c5da in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#38 0x00007fb69fb8e6db in ?? () from /home/user/binaryninja/libQt5Widgets.so.5
#39 0x00007fb69fb2f04c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#40 0x00007fb69fb33488 in QApplication::notify(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Widgets.so.5
#41 0x00007fb69e9dce80 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/user/binaryninja/libQt5Core.so.5
#42 0x00007fb69f2db97b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /home/user/binaryninja/libQt5Gui.so.5
#43 0x00007fb69f2dd485 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /home/user/binaryninja/libQt5Gui.so.5
#44 0x00007fb69f2be6a3 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/binaryninja/libQt5Gui.so.5
#45 0x00007fb692af4720 in ?? () from /home/user/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#46 0x00007fb69caed197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007fb69caed3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007fb69caed49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007fb69ea2c4e7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/binaryninja/libQt5Core.so.5
#50 0x00007fb69e9daefa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/user/binaryninja/libQt5Core.so.5
#51 0x00007fb69e9e2d9d in QCoreApplication::exec() () from /home/user/binaryninja/libQt5Core.so.5
#52 0x0000000000439344 in main ()
#53 0x00007fb69d909830 in __libc_start_main (main=0x4380b0 <main>, argc=0x3, argv=0x7ffdb96a1358, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdb96a1348) at ../csu/libc-start.c:291
#54 0x000000000043fd80 in _start ()
```

**Comment by plafosse** [comment]
I tried to report this on OS X and got an error.
<img width="1138" alt="screen shot 2017-10-12 at 10 10 50 am" src="https://user-images.githubusercontent.com/10556585/31500607-d9277aca-af35-11e7-80e1-063e02fe2bf3.png">

**Comment by plafosse** [comment]
Being that there's been no response I'm closing this issue.
