### ISSUE TITLE
Symbol clash with mediumlevelilinstruction.cpp

### ISSUE THREAD

**Issue by c01db33f** [Vector35/binaryninja-api#854]
(On linux)

There are some template symbols created by mediumlevelilinstruction.cpp which collide between libbinaryninjacore and libbinaryninjaapi. This means that if the compiler/stdlib versions aren't the same between code using the c++ api and whatever configuration is used to build binaryninja, things will go horribly wrong when the core plugins get linked against the mismatching versions of these template functions.

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000005f413c in std::__detail::_Hash_node<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, true>::_M_next() const ()
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
[─────────────────────────────────────────────────────────────────────────REGISTERS─────────────────────────────────────────────────────────────────────────]
*RAX  0x3f800000
*RBX  0x13
*RCX  0x7fffef462c80 ◂— 0x0
*RDX  0x2b
*RDI  0x3f800000
*RSI  0x42
*R8   0x1
 R9   0x0
*R10  0x200
*R11  0x7fffef4e3000 —▸ 0x7fffef800310 ◂— 0x0
*R12  0x13
*R13  0x7fffef4dc314 ◂— 0x1300000000
*R14  0x1
*R15  0x7fffeec87d90 ◂— cmp    byte ptr [rsi + rbp*8 - 1], ah
*RBP  0x7fffffffb0d0 —▸ 0x7fffffffb130 —▸ 0x7fffffffb190 —▸ 0x7fffffffb230 ◂— ...
*RSP  0x7fffffffb0d0 —▸ 0x7fffffffb130 —▸ 0x7fffffffb190 —▸ 0x7fffffffb230 ◂— ...
*RIP  0x5f413c ◂— mov    rdi, qword ptr [rdi]
[───────────────────────────────────────────────────────────────────────────CODE────────────────────────────────────────────────────────────────────────────]
 ► 0x5f413c    mov    rdi, qword ptr [rdi]
   0x5f413f    mov    rax, rdi
   0x5f4142    pop    rbp
   0x5f4143    ret    
 
   0x5f4144    nop    word ptr cs:[rax + rax]
   0x5f414e    nop    
   0x5f4150    push   rbp
   0x5f4151    mov    rbp, rsp
   0x5f4154    sub    rsp, 0x50
   0x5f4158    xor    eax, eax
   0x5f415a    mov    r9b, al
[───────────────────────────────────────────────────────────────────────────STACK───────────────────────────────────────────────────────────────────────────]
00:0000│ rbp rsp  0x7fffffffb0d0 —▸ 0x7fffffffb130 —▸ 0x7fffffffb190 —▸ 0x7fffffffb230 ◂— ...
01:0008│          0x7fffffffb0d8 —▸ 0x5f4ba8 ◂— mov    qword ptr [rbp - 0x38], rax
02:0010│          0x7fffffffb0e0 —▸ 0x8e1700 (BinaryNinja::MediumLevelILInstructionBase::operationOperandIndex) —▸ 0x7fffef43b080 ◂— 0x0
03:0018│          0x7fffffffb0e8 ◂— 0x61 /* 'a' */
04:0020│          0x7fffffffb0f0 ◂— 0x42 /* 'B' */
05:0028│          0x7fffffffb0f8 ◂— 0x3f800000
06:0030│          0x7fffffffb100 ◂— 0x42 /* 'B' */
07:0038│          0x7fffffffb108 ◂— 0x3f800000
[─────────────────────────────────────────────────────────────────────────BACKTRACE─────────────────────────────────────────────────────────────────────────]
 ► f 0           5f413c
   f 1           5f4ba8
   f 2           5f48c8
   f 3           5f3db5
   f 4           5f3a66
   f 5     7fffeeb6e02f
   f 6     7ffff7de76ba call_init.part+154
   f 7     7ffff7de77cb _dl_init+139
   f 8     7ffff7de77cb _dl_init+139
   f 9     7ffff7dec8e2 dl_open_worker+1042
   f 10     7ffff7de7564 _dl_catch_error+116
Program received signal SIGSEGV (fault address 0x3f800000)
pwndbg> bt
#0  0x00000000005f413c in std::__detail::_Hash_node<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, true>::_M_next() const ()
#1  0x00000000005f4ba8 in std::_Hashtable<BNMediumLevelILOperation, std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, std::allocator<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > > >, std::__detail::_Select1st, std::equal_to<BNMediumLevelILOperation>, std::hash<BNMediumLevelILOperation>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash_aux(unsigned long, std::integral_constant<bool, true>) ()
#2  0x00000000005f48c8 in std::_Hashtable<BNMediumLevelILOperation, std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, std::allocator<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > > >, std::__detail::_Select1st, std::equal_to<BNMediumLevelILOperation>, std::hash<BNMediumLevelILOperation>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&) ()
#3  0x00000000005f3db5 in std::_Hashtable<BNMediumLevelILOperation, std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, std::allocator<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > > >, std::__detail::_Select1st, std::equal_to<BNMediumLevelILOperation>, std::hash<BNMediumLevelILOperation>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned long, unsigned long, std::__detail::_Hash_node<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, true>*) ()
#4  0x00000000005f3a66 in std::__detail::_Map_base<BNMediumLevelILOperation, std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > >, std::allocator<std::pair<BNMediumLevelILOperation const, std::unordered_map<BinaryNinja::MediumLevelILOperandUsage, unsigned long, std::hash<BinaryNinja::MediumLevelILOperandUsage>, std::equal_to<BinaryNinja::MediumLevelILOperandUsage>, std::allocator<std::pair<BinaryNinja::MediumLevelILOperandUsage const, unsigned long> > > > >, std::__detail::_Select1st, std::equal_to<BNMediumLevelILOperation>, std::hash<BNMediumLevelILOperation>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](BNMediumLevelILOperation const&) ()
#5  0x00007fffeeb6e02f in ?? () from /home/c01db33f/tools/binaryninja/plugins//libarch_ppc.so
#6  0x00007ffff7de76ba in call_init (l=<optimised out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffe068, env=env@entry=0x7fffffffe080) at dl-init.c:72
#7  0x00007ffff7de77cb in call_init (env=0x7fffffffe080, argv=0x7fffffffe068, argc=2, l=<optimised out>) at dl-init.c:30
#8  _dl_init (main_map=main_map@entry=0x7fffef490a00, argc=2, argv=0x7fffffffe068, env=0x7fffffffe080) at dl-init.c:120
#9  0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffffcd40) at dl-open.c:575
#10 0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffffcd30, errstring=errstring@entry=0x7fffffffcd38, mallocedp=mallocedp@entry=0x7fffffffcd2f, operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, args=args@entry=0x7fffffffcd40) at dl-error.c:187
#11 0x00007ffff7debda9 in _dl_open (file=0x7fffffffd080 "/home/c01db33f/"..., mode=-2147483647, caller_dlopen=0x7ffff6021dab, nsid=-2, argc=<optimised out>, argv=<optimised out>, env=0x7fffffffe080) at dl-open.c:660
#12 0x00007ffff7bd3f09 in dlopen_doit (a=a@entry=0x7fffffffcf70) at dlopen.c:66
#13 0x00007ffff7de7564 in _dl_catch_error (objname=0x7fffef4be250, errstring=0x7fffef4be258, mallocedp=0x7fffef4be248, operate=0x7ffff7bd3eb0 <dlopen_doit>, args=0x7fffffffcf70) at dl-error.c:187
#14 0x00007ffff7bd4571 in _dlerror_run (operate=operate@entry=0x7ffff7bd3eb0 <dlopen_doit>, args=args@entry=0x7fffffffcf70) at dlerror.c:163
#15 0x00007ffff7bd3fa1 in __dlopen (file=<optimised out>, mode=<optimised out>) at dlopen.c:87
#16 0x00007ffff6021dab in ?? () from /home/c01db33f/tools/binaryninja/libbinaryninjacore.so.1
#17 0x00007ffff6024afa in ?? () from /home/c01db33f/tools/binaryninja/libbinaryninjacore.so.1
#18 0x00007ffff6024d20 in BNInitCorePlugins () from /home/c01db33f/tools/binaryninja/libbinaryninjacore.so.1
#19 0x00000000005699f9 in BinaryNinja::InitCorePlugins() ()
#20 0x0000000000604a10 in main ()
#21 0x00007ffff4ed0830 in __libc_start_main (main=0x604990 <main>, argc=2, argv=0x7fffffffe068, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffe058) at ../csu/libc-start.c:291
#22 0x000000000055a929 in _start ()
```
I'm not sure what configuration is used when building binaryninja; but I get the same issue when I build with either my system gcc or with a trunk clang/libstdc++.

I haven't looked at the CLA yet, so can't create a pull request but fixing this issue is very straightforward; the cmake target property CXX_VISIBILITY_PRESET allows controlling the default symbol visibility.

**Comment by rssor** [comment]
Fixed in build 1.1.1231-dev.
