### ISSUE TITLE
install_api.py for Windows fails

### ISSUE THREAD

**Issue by 0x00xx** [Vector35/binaryninja-api#879]
> python install_api.py
    Binary Ninja not found. Please provide the path to Binary Ninja's install directory: [r'C:\Program Files\Vector35\BinaryNinja\python'] : C:\Program Files\Vector35\BinaryNinja\python
    Traceback (most recent call last):
      File "install_api.py", line 53, in <module>
        while not validate_path(api_path):
      File "install_api.py", line 44, in validate_path
        from binaryninja import core_version
      File "C:\Program Files\Vector35\BinaryNinja\python\binaryninja\__init__.py", line 27, in <module> import _binaryninjacore as core
  File "C:\Program Files\Vector35\BinaryNinja\python\binaryninja\_binaryninjacore.py", line 18, in <module>
    core = ctypes.CDLL(os.path.join(_base_path, "binaryninjacore.dll"))
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

I tried to manually fix it, but it didn't work. I have bninja installed in this path: "C:\Program Files\Vector35\BinaryNinja"

**Comment by joshwatson** [comment]
You're probably using 32 bit Python.

**Comment by 0x00xx** [comment]
Oh, didn't know it only works with 64bit.
Yeah I'm using 32 bit python
