### ISSUE TITLE
get_function_at crashes in a file without a platform

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#916]
To reproduce:
1. Ctrl+N
2. `bv.get_function_at(0)`
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/whitequark/Applications/binaryninja/plugins/../python/binaryninja/binaryview.py", line 2098, in get_function_at
    func = core.BNGetAnalysisFunction(self.handle, plat.handle, addr)
AttributeError: 'NoneType' object has no attribute 'handle'
```
Should do `if plat:` etc.

**Comment by bpotchik** [comment]
Fixed in build 1.1.1043-dev.
