### ISSUE TITLE
Implement create_graph method for LowLevelILFunction and MediumLevelILFunction

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#925]
`Function.create_graph()` returns a `FunctionGraph` that can be used for things like the `export_svg.py` script, but there is not an analogous method for `LowLevelILFunction` and `MediumLevelILFunction` classes. It would be nice if these could be implemented as well.

**Comment by joshwatson** [comment]
I was hoping it was as easy as changing the handle, but alas:

```
>>> llfg = FunctionGraph(current_function.view, core.BNCreateFunctionGraph(current_function.low_level_il.handle))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/_binaryninjacore.py", line 1425, in BNCreateFunctionGraph
    result = _BNCreateFunctionGraph(*args)
ArgumentError: argument 1: <type 'exceptions.TypeError'>: expected LP_BNFunction instance instead of LP_BNLowLevelILFunction
```

**Comment by joshwatson** [comment]
Thanks to rss on slack, I've learned that the proper way to do this is via the following:

```
>>> fg = current_function.create_graph()
>>> fg.layout_and_wait(FunctionGraphType.LowLevelILFunctionGraph)
>>> fg.blocks
[<graph block: x86_64@0x0-0x1>, <graph block: x86_64@0x1-0x5>, <graph block: x86_64@0x5-0xc>, <graph block: x86_64@0xc-0x12>, <graph block: x86_64@0x12-0x15>, <graph block: x86_64@0x15-0x16>, <graph block: x86_64@0x16-0x19>, <graph block: x86_64@0x19-0x1c>, <graph block: x86_64@0x1c-0x21>, <graph block: x86_64@0x21-0x26>, <graph block: x86_64@0x26-0x2b>, <graph block: x86_64@0x2b-0x2d>, <graph block: x86_64@0x2d-0x30>, <graph block: x86_64@0x30-0x33>, <graph block: x86_64@0x33-0x38>, <graph block: x86_64@0x38-0x44>, <graph block: x86_64@0x44-0x47>, <graph block: x86_64@0x47-0x4f>, <graph block: x86_64@0x4f-0x50>, <graph block: x86_64@0x50-0x53>, <graph block: x86_64@0x53-0x56>, <graph block: x86_64@0x56-0x5b>, <graph block: x86_64@0x5b-0x5d>]
```
