### ISSUE TITLE
Function.get_indirect_branches_at broken

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#995]
```
>>> current_function.get_indirect_branches_at(here)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/function.py", line 1145, in get_indirect_branches_at
    result.append(IndirectBranchInfo(architecture.CoreArchitecture._from_cache(branches[i].sourceArch), branches[i].sourceAddr, architecture.Architecture(branches[i].destArch), branches[i].destAddr, branches[i].autoDefined))
TypeError: __init__() takes exactly 1 argument (2 given)
```

`Architecture.__init__` doesn’t take a parameter, so my guess is that should just be `branches[i].destArch` not `architecture.Architecture(branches[i].destArch)`

**Comment by rssor** [comment]
Fixed in build 1.1.1137-dev.
